### ISSUE TITLE
Gulp-watch doesn't appear to be working

### ISSUE THREAD

**Issue by skawaguchi** [floatdrop/gulp-watch#108]
This is a repeat of my [SO post](http://stackoverflow.com/questions/27021570/gulp-watch-gulp-watch-less-dont-fire). Please let me know whether I'm doing something wrong, or whether it's a legit bug.

I'm having trouble getting [gulp-watch](https://www.npmjs.org/package/gulp-watch) or [gulp-watch-less](https://www.npmjs.org/package/gulp-watch-less) to fire after following the documented examples. I originally through the problem was with lazypipe (not shown here), but it appears to me that I'm doing something wrong in the way I'm using the plugins. Here's my dumbed-down code which is still not working.

Note that I tried this with plain gulp-watch and it exhibits the exact same issue: it doesn't trigger subsequent pipes on change. I'll include info around that here in case that's the problem.

Here's my gulpfile.

```
var debug = require ( 'gulp-debug' );
var gulp = require ( 'gulp' );
var less = require ( 'gulp-less' );
var watchLess = require ( 'gulp-watch-less' ); 

gulp.task ( 'dev-watch', function () {
  // main.less just imports child less files
  gulp.src ( './app/styles/less/main.less' )
    .pipe ( watchLess ( './app/styles/less/main.less' ) )
    .pipe ( debug () );
    .pipe ( less () )
    .pipe ( gulp.dest ( './app/styles' ) )
  ;
});
```

When I start the task, it executes and generates the expected files perfectly. I see debug output the stream info just fine as well. 

When I change a file I see that watchLess is picking up the change: 

```
 [10:49:54] LESS saw child.less was changed
 [10:49:54] LESS saw child.less was changed
 [10:49:54] LESS saw main.less was changed:by:import
 [10:49:54] LESS saw main.less was changed:by:import
```

However, the less task doesn't execute. It doesn't appear to be emitting anything because debug doesn't fire.

Here's the pertinent package.json info:

```
"devDependencies": {
  "gulp": "^3.8.7",
  "gulp-less": "^1.3.6",
  "gulp-watch": "^1.2.0",
  "gulp-watch-less": "^0.2.1"
}
```

**Comment by stevenjlho** [comment]
When i change CSS or JavaScript file,  gulp-watch execute perfectly, but Terminal can not display any log message, such as `xxx.css was changed`. Gulp-watch version is 4.1.0

**Comment by floatdrop** [comment]
@stevenjlho use `verbose: true` option.

**Comment by lyradesigns** [comment]
Thank you, that was a life-saver, I included it in a few stackoverflow issues as well.

**Comment by lmx99** [comment]
the best solution

```
var combiner = require('stream-combiner2');

var combined = combiner.obj([
    gulp.src(srcs),
    less(),
    autoprefixer({
        browsers: ['last 6 versions'],
        cascade: false
    }),
    isDev ? null : cleanCss(),
    gulp.dest(targetDir + 'css/multi/'),
].filter(v => v));

// any errors in the above streams will get caught
// by this listener, instead of being thrown:
combined.on('error', console.error.bind(console));
combined.on('end', () => {}); //done have been call when return combined;
return combined;
```
