### ISSUE TITLE
Update Gaze version to 0.6.4

### ISSUE THREAD

**Issue by kaldrenon** [floatdrop/gulp-watch#117]
Per `gaze` patch notes, version 0.6.4 includes: `Use graceful-fs to avoid EMFILE errors in other places fs is used`

I'm using `gulp-watch` in several tasks which can watch a large number of files at a time. Some of my team members frequently encounter EMFILE errors, and I would like to take advantage of this `gaze` update.

Full notes:

    0.6.4 - Catch and emit error from readdir (@oconnore). Fix for 0 maxListeners. Use graceful-fs to
    avoid EMFILE errors in other places fs is used. Better method to determine if pathwatcher was built.
    Fix keeping process alive too much, only init pathwatcher if a file is being watched. Set min required
    to Windows Vista when building on Windows (@pvolok).

**Comment by Dashed** [comment]
May I suggest possibility to switch to:
- https://github.com/paulmillr/chokidar
- https://github.com/webpack/watchpack

**Comment by floatdrop** [comment]
@Dashed yeah, it's been a while. Let's do this.

@UltCombo do you have any feedback about chokidar?

**Comment by UltCombo** [comment]
@floatdrop I've used it in some other projects, it looks like it works ok but I haven't tested it throughout.

**Comment by Dashed** [comment]
@floatdrop Awesome thanks! Everything seems to be more stable.
