### ISSUE TITLE
Ignore not exist folder

### ISSUE THREAD

**Issue by movie4** [floatdrop/gulp-watch#119]
Hello

Watch task, get array of files like: 
`watch(['**/*js, '!__temp'],  function() { //do something })`

`__temp` folder doesn't exist when `watch` task running, other task create folder `__temp`, and `watch` run.

Is it possible to add non-existent folder to ignore list of files and not run `watch` task on it

**Comment by floatdrop** [comment]
@movie4 gulp-watch@4.0.1 now works as expected with this.
