### ISSUE TITLE
not compatible with gulp-mocha?

### ISSUE THREAD

**Issue by dashed** [floatdrop/gulp-watch#12]
gulp-watch doesn't seem to be compatible with gulp-mocha

**Comment by IanVS** [comment]
@floatdrop, when you say "don't use streaming mode", does that mean there is another mode which does work with gulp-mocha?

**Comment by floatdrop** [comment]
@IanVS this was, like, a year ago - may be you can now pipe safely into gulp-mocha (like [readme says](https://github.com/sindresorhus/gulp-mocha#usage)).

**Comment by IanVS** [comment]
It wasn't working for me, but it could have been due to something else.  I searched everywhere in the repo for `gulp-mocha`, and strangely enough the README was not in the results.  I've found another way to do what I need.
