### ISSUE TITLE
Setting delay/interval on watcher

### ISSUE THREAD

**Issue by xeor** [floatdrop/gulp-watch#121]
I have a watch that uses a lot of cpu because of the watcher.
With `gulp.watch`, I could set settings like `{ interval: 500 }` to make it check for files every 500ms, instead of the default 100ms.
However, I cant find any options to do that with `gulp-watch`. Is there any? Is it done another way? Or is this something that isn't implemented yet?

**Comment by Gerst20051** [comment]
if anyone is having an issue with watch taking up to 10-15 seconds to detect a change please refer to this issue. https://github.com/gulpjs/gulp/issues/448

**Comment by floatdrop** [comment]
@Gerst20051 I don't think this issue is relevant to `gulp-watch`, because it uses [chokidar](http://npmjs.com/chokidar) - which is more robust.
