### ISSUE TITLE
Watch doesn't see new files when files path begins with './'

### ISSUE THREAD

**Issue by kasperekt** [floatdrop/gulp-watch#122]
With that code (notice: `./`):

````javascript
watch('./frontend/templates/**/*.jade', gulpTemplates);
````

plugin seemed to not see new files, but I found some solution on main `gulp` repo, that when I write the path without `./` it works fine. Like this:

````javascript
watch('frontend/templates/**/*.jade', gulpTemplates);
````

**Comment by floatdrop** [comment]
Duplicate of https://github.com/floatdrop/gulp-watch/issues/111
