### ISSUE TITLE
gulp-watch not playing nicely with gulp-ruby-sass

### ISSUE THREAD

**Issue by scottrogowski** [floatdrop/gulp-watch#124]
I can't deduce which package this is related to but I thought I would bring it up here first. See this http://stackoverflow.com/questions/27933561/issue-with-piping-gulp-watch-into-gulp-ruby-sass?rq=1 and this (created by me) http://stackoverflow.com/questions/28079466/gulp-ruby-sass-not-working-with-gulp-watch

**Comment by floatdrop** [comment]
This issue does not belongs here. As documentation says - pre 1.0 version are not supported (and probably broken) - use 1.0-alpha https://github.com/sindresorhus/gulp-ruby-sass/tree/rw/1.0

To launch recompilation you can use callback mode:

```js
watch('sass/**/*.scss', function () {
    sass('sass/').pipe(gulp.dest('build'));
});
```
