### ISSUE TITLE
More logging options? Disable add event on startup?

### ISSUE THREAD

**Issue by PaperElectron** [floatdrop/gulp-watch#125]
So I just updated to the 4.0 branch during some spring cleaning of our apps dependencies. Now when I start gulp, I notice watch isnt telling me when files are changed/added, no big deal, turn on verbose... OMG!! 1000 lines of log output, one for every file in the application that watch is watching (All of them, really).

Is there any way to suppress this, and still see the changes that are happening after startup?

**Comment by floatdrop** [comment]
It shouldn't log, unless you enabled `verbose` option.

**Comment by floatdrop** [comment]
Related commit - e708c7b

**Comment by PaperElectron** [comment]
@floatdrop, right but its binary now, it just logs everything, so if I want to see a file change when its actually relevant, I have to see 1000 lines of every file that was added to the watcher?

**Comment by floatdrop** [comment]
@PaperElectron oh, I get it now. As workaround you can add `data` listener with `if` statement inside - that will filter by `event` property and log file path. Can you tell, what is your use case?

**Comment by PaperElectron** [comment]
I had started to explore that option, but it was going to involve incrementing counters and such, to restart the logging after the initial wave of files was added. I didn't think that was appropriate inside of a task.

Use case? Every file in my application is being watched one way or another by different tasks, I want to see changes when I save, add etc. But getting individual log output that gulp-watch did indeed add all 900 of my files at startup is a bit much, lol. 

Would it be to difficult to add a summary line at startup, and then continue logging as usual afterwards? Possibly meld some of the gulp-batch stuff in to catch the first n milliseconds of output then carry on as usual?

**Comment by floatdrop** [comment]
@PaperElectron I would like to move this functionality to separate module (something like [gulp-debug](https://github.com/sindresorhus/gulp-debug/)) - which can use gulp-batch inside and be suited for endless stream of events.

Sorry for not reading whole issue at once :dog:

**Comment by floatdrop** [comment]
@PaperElectron now you can update to `4.1.0` and enable `verbose` to get desired behavior.

**Comment by PaperElectron** [comment]
Awesome @floatdrop, thanks!
