### ISSUE TITLE
v4 appears to be emitting on ready (initial load)

### ISSUE THREAD

**Issue by OverZealous** [floatdrop/gulp-watch#126]
I have a watch process that basically has the normal watch dependent on the normal build.

With v3, this worked as expected: everything would be built once, then the watchers would start watching, then I start BrowserSync and Karma.  Then only _new_ changes would trigger builds of files.

With v4, apparently the files are built the first time the watcher sees them.  This completely breaks my build process, as I have to wait for everything to be built **twice** before I can start work.

I can't easily remove the build step from my process (I tried), because then none of the files exist until after the servers are already started, throwing various errors.

It would be nice to be able to delay the first emit until after the `ready` event has happened.

(Also, as a side note: you are currently hard-coding the `opts.events` property, so it's impossible to override.)

**Comment by floatdrop** [comment]
@OverZealous yeah, thats how `chokidar` works - it first emits `ready` event and then series of `add` for files, that has been added to watcher or on file-system (am I right @es128?).

`opts.events` is fixed in `4.0.3` - you can disable `add` event and react only on changed files, but still it will be workaround.

This issue also connected with #125.

**Comment by es128** [comment]
You can change this behavior with the `ignoreInitial` option. @floatdrop you may want to set it it true by default for your users.

**Comment by floatdrop** [comment]
@es128 thanks, that's should solve it!

**Comment by floatdrop** [comment]
@OverZealous You can update to `4.1.0` version or set `ignoreInitial: true` in options.

**Comment by es128** [comment]
Btw, regarding your earlier statement, the `add` events from the initial crawl come **before** the `ready` event.

**Comment by OverZealous** [comment]
Thanks for the quick response!

4.1.0 appears to be working perfectly.  I also feel like watch is picking up changes faster, so this is great.  (This is after using `osx-ulimit` to crank the open file limit way up.)

**Comment by es128** [comment]
Fyi fsevents doesn't open fds so fiddling with the ulimit may not be necessary anymore, but YMMV and it probably won't hurt anything.

**Comment by OverZealous** [comment]
@es128 Thanks for the heads up, if I get a chance, I'll see if I can strip that out of our build process.

It might still be necessary due to Karma (which still opens a thousand files).

**Comment by es128** [comment]
They use graceful-fs, so that should at least avoid occurrence of any EMFILE errors, but yeah it'll be more performant if you can avoid graceful's incremental backoff ever needing to kick in.

**Comment by PaperElectron** [comment]
@OverZealous Does 4.10 have the same behavior as the 3.x branch for you? 

> With v3, this worked as expected: everything would be built once, then the watchers would start watching, then I start BrowserSync and Karma. Then only new changes would trigger builds of files

With the default config (ignoreInitial: true) it doesn't seem to be building files on startup, which I was pretty certain It did in the 3.x branch. Setting ignoreInitial: true, builds the files as expected, but basically reopens #125, in that I now have to look at a giant wall of add events in the console if I want verbose output on changes.

**Comment by floatdrop** [comment]
@PaperElectron to build files on initial load you can `gulp.src(globs).pipe(watch(...))`.

**Comment by PaperElectron** [comment]
@floatdrop thats different than before right?

**Comment by floatdrop** [comment]
@PaperElectron nope, in v3 it was just like this - https://github.com/floatdrop/gulp-watch/tree/5397da21bc190852be6f5a593d1c2ffe711f534c#usage

**Comment by PaperElectron** [comment]
@floatdrop I must have been on a super old version then, because https://github.com/floatdrop/gulp-watch/tree/master/docs#incremental-build that is how all of my gulp-watch stuff was set up.

**Comment by es128** [comment]
but if you pass the `ignoreInitial: false` option then that method should still work, right?

**Comment by PaperElectron** [comment]
@es128 But then with verbose: true so I can see changes, I have to look at 1000 lines of console spam telling be it added every file its watching in the project at startup.

**Comment by es128** [comment]
choices, choices

**Comment by PaperElectron** [comment]
@es128, yeah, its not like Im in the business of actively developing my build process, I just write what I need and update libraries when I come across them, sometimes it leads to stuff like this, lol.
