### ISSUE TITLE
`cwd` option for relative paths does not work anymore

### ISSUE THREAD

**Issue by julien-f** [floatdrop/gulp-watch#129]
It seems that since the switch to choikidar, the `cwd` option is no longer supported therefore paths relative to a different directory than the current one are no longer watched.

Example of use which is now broken:

```javascript
gulp.task('copyFiles', function copyFiles() {
  return gulp.src('*', { cwd: SRC_DIR })
    .pipe(gulpWatch('*', { cwd: SRC_DIR }))
    .pipe(gulp.dest(DIST_DIR))
  ;
});
```

**Comment by es128** [comment]
Yes, chokidar and gaze do not have identical APIs. 

How about `process.chdir(SRC_DIR)`?

**Comment by julien-f** [comment]
It works for this specific use case but I don't like it because:

1. `gulp-watch()` does not work anymore like `gulp.src()`;
2. it is a global setting, therefore tasks are not independent anymore.

**Comment by es128** [comment]
Well, with that solution you could make `gulp.src()` look exactly the same, and gulp is on the verge of switching to chokidar too for gulp v4. But your second point is valid. I can see that more is going to have to be done to shim the differences between the gaze and chokidar APIs.

**Comment by es128** [comment]
I just added equivalent `cwd` functionality to chokidar in 1.0.0-rc3

**Comment by julien-f** [comment]
@es128 You rock!

**Comment by julien-f** [comment]
Tested: works for me.

Thank you so much @es128!
