### ISSUE TITLE
Option to assume all files changed on startup

### ISSUE THREAD

**Issue by simonzack** [floatdrop/gulp-watch#131]
Could there be an option like this? Gulp dies when there are build errors and I'm left in a partially built state, not knowing which files were built and which weren't. This saves me from writing the same pipe twice:

    gulp.src('src/*.js').pipe(...)
    gulp.watch('src/*.js').pipe(...)

But I'm still rather new to gulp, maybe there's an easier way without introducing another option?

**Comment by Dashed** [comment]
May need other plugins for this:

https://github.com/sindresorhus/gulp-changed
https://github.com/gulpjs/gulp#incremental-builds

**Comment by floatdrop** [comment]
@simonzack you can use `ignoreInitial: false` option.

**Comment by simonzack** [comment]
> @simonzack you can use ignoreInitial: false option.
Thanks, that works great with my streams but it doesn't appear to call my callbacks, is there a way to make it work with callbacks?

**Comment by floatdrop** [comment]
@simonzack it should call callbacks because of this code - https://github.com/floatdrop/gulp-watch/blob/master/index.js#L88-L89

First line sends it to stream, second calls your callback.

**Comment by simonzack** [comment]
Does indeed, thanks.
