### ISSUE TITLE
v4 triggers non-sense events

### ISSUE THREAD

**Issue by gustavohenke** [floatdrop/gulp-watch#133]
I just migrated to gulp-watch 4.1.0, and it's triggering some non-sense events for me.
I recorded two videos from my IDE (they're smaller than gifs, although not so cool!):

* Change .yml file, but a random .js is detected as changed
  https://docs.google.com/file/d/0B5uvgO7NPTE9ZjBDUElGMmVjNU0/edit?usp=drivesdk
* Change .js file, lots of events are triggered
  https://docs.google.com/file/d/0B5uvgO7NPTE9d3RjNXQ1WlJtRnc/edit?usp=drivesdk

When using gulp-watch v3, I didn't have such problems.

**Comment by gustavohenke** [comment]
Obviously, I forgot about the watch tasks I have:

```js
$.watch([ "src/**/*.js" ] function ( file ) {
      // Do this so only modified files are processed
      USED_JS_SOURCES = gulp.src( file.path, {
          base: file.base
      });
      gulp.start( "js" );
});
```

and

```js
$.watch([ "src/**/i18n/*.yml" ], function () {
      gulp.start( "i18n" );
});
```

I also have tasks for .html and .less files. .html fall into the first problem (although its tasks are run), and .less files fall into the second problem.

**Comment by floatdrop** [comment]
@gustavohenke IDE can touch those files. Can you confirm, that `touch` command from console triggers it as well?

**Comment by gustavohenke** [comment]
It did not work:
https://docs.google.com/file/d/0B5uvgO7NPTE9OVhLRkZTeDRrTVk/edit?usp=drivesdk

**Comment by floatdrop** [comment]
@gustavohenke I have only one guess left - you change files in `js` task, that currently being watched.

**Comment by gustavohenke** [comment]
Sorry, I think I didn't understood you.

**Comment by floatdrop** [comment]
Some task possibly can write in file, that being watched.

**Comment by gustavohenke** [comment]
OK, I managed to narrow it down.

The project:
![](http://i.imgur.com/WQH2hKV.png)

The deps:
```
@ C:\Users\Gustavo\Projetos\tst
├── gulp@3.8.11
└── gulp-watch@4.1.1
```

The video: https://docs.google.com/file/d/0B5uvgO7NPTE9U09BeDhOOFlpRWM/edit?usp=drivesdk

Do you see?
gulp-watch is receiving change events for globs like `filename*`.

**Comment by floatdrop** [comment]
@gustavohenke thanks for details! But I can't reproduce it. Can you check this one-liner?:

```js
require('chokidar').watch('.', {ignored: /[\/\\]\./}).on('all', function(event, path) {
  console.log(event, path);
});
```

**Comment by gustavohenke** [comment]
Yeah, it keeps occurring. So it seems like it's not your problem. But I found that in a Ubuntu 13.10 installation this does not occur.
However, I've now realized that I forgot to mention that my OS is Windows 8.1 :disappointed:

**Comment by floatdrop** [comment]
@gustavohenke could you open issue in `chokidar` please?

//сс @es128

**Comment by gustavohenke** [comment]
@floatdrop, I created a test repository: https://github.com/gustavohenke/watch-events-problem
Try modifying some file inside `src/`, the errors may happen (if you're using Windows).

**Comment by gustavohenke** [comment]
Closing this issue as paulmillr/chokidar#231 has been fixed!
