### ISSUE TITLE
Negated glob patterns doesn't work

### ISSUE THREAD

**Issue by HarryBurns** [floatdrop/gulp-watch#134]
Hello!

I found out that negated glob patterns are ignored. For example this watch:
``` javascript
    watch(
        [
            './src/**/*',
            '!./src/dont_touch_me.js',
        ],
        {
            name: 'testWatcher watcher',
            verbose: 'true'
        }, function (vinyl) {
            gulp.start('build');
        });
```
will be triggered even if we'll change `dont_touch_me.js`

It's not a GLOB issue cause if we `gulp.src()` the same glob - everything is OK.

I create a little runnable for testing: http://runnable.com/VNLRg0Oy2whScedI/test-for-glob-issue-for-gulp-watch-for-node-js-and-hello-world. You will unable to change files in that runnable, but you can fork it.

Can you fix that issue please?

**Comment by HarryBurns** [comment]
I've created a gist for that issue https://gist.github.com/HarryBurns/655a5a797ad7bce4ca3d

**Comment by floatdrop** [comment]
I'm not sure, but this seems like duplicate of #1 

Try to remove `./` from beginning of glob:

```js
watch(
        [
            'src/**/*',
            '!src/dont_touch_me.js',
        ],
        {
            name: 'testWatcher watcher',
            verbose: 'true'
        }, function (vinyl) {
            gulp.start('build');
        });
```

**Comment by HarryBurns** [comment]
Sorry for duplicate issue. Yes, removing `./` from the beginning of glob helps.
Thank you!

But it's strange, that glob of `gulp.src` and glob of `gulp-watch` work in different ways.
