### ISSUE TITLE
Problems when using non-glob paths

### ISSUE THREAD

**Issue by HeyImAlex** [floatdrop/gulp-watch#135]
The issue is [here](https://github.com/floatdrop/gulp-watch/blob/master/index.js#L60).

You're using glob-parent to get the base if one isn't explicitly set, but glob-parent doesn't work properly on non-glob paths.

```js
var globParent = require('glob-parent');
globParent('some/path.html');
// 'some/path.html'
```

So that makes `opts.base` equal to the actual filename, which makes `vinyl.relative` an empty string. Especially bad since vinyl-fs uses relative in dest, so the file will be written to whatever string was given to dest.

Noticed this when using 4.1.0 and logging didn't display anything for the matched filename.

Temporary fix: explicitly provide base for any non-glob paths.

**Comment by floatdrop** [comment]
@HeyImAlex Nice catch! Fixed in `4.1.1`.
