### ISSUE TITLE
How to filter files to watch?

### ISSUE THREAD

**Issue by artem-malko** [floatdrop/gulp-watch#137]

**Comment by artem-malko** [comment]
For  example i've got a folder with css-files and i'd like to watch for them. But i'd like to not watch for one css-file.
So:

```javascript
watch('./folder-to-watch/**/*.css', function(vinyl) {
    log(vinyl.event);
});
```
Where (or how) should i add the path to ignored file?

**Comment by floatdrop** [comment]
As [node-glob](https://github.com/isaacs/node-glob#glob-primer) docs says:

```js
watch(['!folder-to-watch/that-one.css','folder-to-watch/**/*.css'], function(vinyl) {
    log(vinyl.event);
});
```

**Comment by artem-malko** [comment]
Yeah, thanks. It doesn't work, if i use './' in glob pattern(
https://github.com/isaacs/node-glob#dots I think, that dot:true could fix it, doesn't it? How can i set option of glob «dot» to true?

**Comment by floatdrop** [comment]
@artem-malko it is known bug with `./` in globs - #1, so don't use `./`, just type path without it.

**Comment by artem-malko** [comment]
Ok, but could it helps, to set dot to true?

**Comment by floatdrop** [comment]
@artem-malko I don't think [chokidar](https://github.com/paulmillr/chokidar) uses node-glob for path's actually, so there is no `dot` option unfortunately.

**Comment by artem-malko** [comment]
Excuse me, but one more question)

What the difference between 'folder-name/*.css' and './folder-name/*.css' if we have a fs like this:

```
├── gulpfile.js
└── folder-name

**Comment by floatdrop** [comment]
@artem-malko I'm not aware of any difference between `folder-name/.css` and `./folder-name/.css` in this case.

**Comment by artem-malko** [comment]
Ok, thanks a lot)
