### ISSUE TITLE
Saving directly from Fireworks triggers an error ('EBUSY')

### ISSUE THREAD

**Issue by lcdsantos** [floatdrop/gulp-watch#139]
I'm trying to export an image directly from Fireworks to a folder in my project, but I'm getting this error:

![captura de tela 2015-02-25 17 47 31](https://cloud.githubusercontent.com/assets/910974/6380168/6955618a-bd16-11e4-947f-32eca8c133ed.png)

`gulpfile.js`:
```js
var gulp  = require('gulp');
var watch = require('gulp-watch');

/* Default task */
gulp.task('default', function() {
  watch(['./img/src/*'], function(vinyl) {
    console.log(vinyl, vinyl.event);
  }).on('error', function(err) {
    console.log('err: ', err);
  });
});
```

Maybe it's because `watch` tries to read the file before it finished saving?
Am I doing something wrong? There's a way to prevent this?

**Comment by leggomuhgreggo** [comment]
Hey, I'm dealing with a similar issue
```
events.js:141
      throw er; // Unhandled 'error' event
Error: EBUSY: resource busy or locked, open ....
```
Have a gulp watch on some LESS files. Some people on my team use Dreamweaver. When they download over FTP, Dreamweaver hold onto the file to check if the user wants to do a file compare between remote and local. Causes the ebusy error.

I'm debugging, but if anyone has any thoughts I'd be most appreciative!

**Comment by leggomuhgreggo** [comment]
Update: I just used the `readDelay` option. Not ideal but it solves the problem.

Would it make sense to try and catch the error to test if its `EBUSY` and rerun after and interval? Something like that would alleviate having to wait for the readDelay all the time.

Thanks

**Comment by lcdsantos** [comment]
Hey @leggomuhgreggo, I ended up doing something like this:
```js
var gulp  = require('gulp');
var util  = require('gulp-util');
var watch = require('gulp-watch');

gulp.task('imagemin', function() {
  // code for imagemin task
});

/* Default task */
gulp.task('watch', function() {
  return watch(['./img/src/*'], {
    verbose: true
  }, function() {
    gulp.start('imagemin');
  })
  .on('error', function(err) {
    var colors = util.colors;
    util.log(colors.yellow('Error:', err.code), '»', colors.green(err.path));
    return true;
  });
});

gulp.task('default', ['watch']);
```

By returning `true` on the error callback, you make code keep running, until the `changed` event triggers.

**Comment by leggomuhgreggo** [comment]
Ahhh that's perfect thanks @lcdsantos

**Comment by UltCombo** [comment]
You can set the [`awaitWriteFinish` option](https://github.com/paulmillr/chokidar#performance) to properly resolve this issue.

I'm considering to remove the `readDelay` option in the next major version in favor of Chokidar's `awaitWriteFinish` option.
