### ISSUE TITLE
Braced sections in glob fails for v4+

### ISSUE THREAD

**Issue by jasperkuperus** [floatdrop/gulp-watch#140]
Since v4 of gulp-watch, the braced sections seem to break the watch. See this example:

```coffee
gulp  = require 'gulp'
watch = require 'gulp-watch'
print = require 'gulp-print'

watchPath = '{./src/**/*.coffee,./bin/**/*.coffee}'

gulp.task 'do', (cb) ->
  gulp.src    watchPath
  .pipe watch watchPath
  .pipe print()
```

I've narrowed this down to an [issue of chokidar](https://github.com/paulmillr/chokidar/issues/241). However, this did work in `gulp-watch` version 3.

**Comment by floatdrop** [comment]
Why don't use ```['./src/**/*.coffee','./bin/**/*.coffee']``` in this case?

**Comment by jasperkuperus** [comment]
Yes, I am using that now. But as the braced sections worked in gulp 3, an update to gulp 4 suddenly broke my setup. Also, the documentation on npmjs references [node-glob](https://github.com/isaacs/node-glob) which tells you this is possible. I figure there might be more people who run into this problem?

**Comment by floatdrop** [comment]
@jasperkuperus in v3 gulp-watch was based on `gaze`, now we using `chokidar`. Documentation on nodejs is bit outdated. Recent docs does not contains reference on `node-glob` now. I think chokidar is not implemented full node-glob spec yet. You can open issue about it there.

**Comment by jasperkuperus** [comment]
@floatdrop I've done a bit more testing and discovered that directly using chokidar with this glob works like a charm. All events are reported as they should be. So, apparently something is going wrong in gulp-watch rather than chokidar after all.

**Comment by jasperkuperus** [comment]
Somehow, `chokidar.watch().on('all')` does not fire for this glob, but if you listen on `raw` in stead of `all`, you will get events for this glob. Does that help you?

**Comment by floatdrop** [comment]
@jusperkuperus that's wired, could you open issue in chokidar repo for this? This would be awesome.

/cc @es128

**Comment by es128** [comment]
If you're only seeing the events emitted under `raw` then there is a problem - they're getting filtered out. gulp-watch should not be listening to `raw`

**Comment by jasperkuperus** [comment]
Ok, you're right. Check the following snippet. Try it, you will only get raw events in this scenario.

```javascript
var chokidar = require('chokidar');

var watcher = chokidar.watch(['{./src/**/*.coffee,./bin/**/*.coffee}']);

var log = console.log.bind(console);

watcher
  .on('add', function(path) { log('Add File', path, 'has been added'); })
  .on('addDir', function(path) { log('Add Directory', path, 'has been added'); })
  .on('change', function(path) { log('Change File', path, 'has been changed'); })
  .on('unlink', function(path) { log('Unlink File', path, 'has been removed'); })
  .on('unlinkDir', function(path) { log('Unlink Directory', path, 'has been removed'); })
  .on('error', function(error) { log('Error happened', error); })
  .on('ready', function() { log('Initial scan complete. Ready for changes.'); })
  .on('raw', function(event, path, details) { log('Raw event info:', event, path, details); })
```
