### ISSUE TITLE
Only one change detected for non-glob patterns with atomic save

### ISSUE THREAD

**Issue by julien-f** [floatdrop/gulp-watch#141]
When the pattern does not contain a glob and the file is saved atomically (copy and move over, like SublimeText does), only the first change is detected.

```javascript
var gulp = require('gulp');
var watch = require('gulp-watch');

gulp.task('default', function () {
  return watch('foo.txt', {
    verbose: true,
  });
});
```

If the file is just touched (`touch foo.txt`) it works normally but if it is replaced (`cp foo.txt _tmp && mv -f _tmp foo.txt`) then the watch breaks.

If the pattern contains a glob (`foo*.txt`) then it works as it should.

/cc @es128.

**Comment by es128** [comment]
Well, the difference isn't between globs and non-globs, it's between watching a directory (globs effectively watch a directory with a filter) and watching an individual file.

I'm assuming you're encountering this on Linux?

**Comment by julien-f** [comment]
Indeed, Debian 8.

**Comment by julien-f** [comment]
So, do you consider it as a bug or should I use a work around?

**Comment by es128** [comment]
Probably a bug. Need to investigate  

But by all means - use a workaround for now since it's easy.

**Comment by julien-f** [comment]
For information, I think the best workaround is to use a character class for a single character:

```javascript
var gulp = require('gulp');
var watch = require('gulp-watch');

gulp.task('default', function () {
  return watch('[f]oo.txt', {
    verbose: true,
  });
});
```

**Comment by DarkPark** [comment]
the problem is still exist
version: 4.3.5
gulp-watch detects only the first single file change and nothing after it

```js
// less
watch([
	path.join(global.paths.app, 'less', '**', '*.{less,js}'),   // <--- all these files changes are well detected
	path.join(global.paths.config, 'metrics.js')   // <--- only the first change
], function () {
	gulp.start('less:develop');
});
```

**Comment by es128** [comment]
Crossref https://github.com/paulmillr/chokidar/issues/237

**Comment by DarkPark** [comment]
I see
but the suggested solution is difficult to call elegant

**Comment by es128** [comment]
Nobody called it elegant. It's a thankfully simple, albeit ugly, workaround for a bug that hasn't been squished yet.

**Comment by DarkPark** [comment]
anyway thanks for pointing me in the right direction

**Comment by UltCombo** [comment]
This seems to have been fixed upstream.

Please comment/reopen if you are still experiencing this issue.
