### ISSUE TITLE
Doesn't seem to play with browsersync?

### ISSUE THREAD

**Issue by siliconalchemy** [floatdrop/gulp-watch#142]
Using gulp-watch for 'incremental' updates works great, in the task below it only recompiles a single markup file.  However, it doesn't seem to fire the browsersync for some reason, which works in every other task I'm using, including gulp-watch in non-pipe mode.  Is this a known issue, or does it work for other people?
```
        return gulp.src(config.paths.src.jadePath+'/*.jade')
            .pipe(plugins.watch(config.paths.src.jadePath+'/*.jade', {verbose: true}).on('data', function(file){console.log(file);}))
            .pipe(plugins.jade()
            .pipe(gulp.dest(config.paths.dest.basePath))
            .pipe(plugins.tap(function (file,t) {
                console.log(file.path);
            }))
            .pipe(browserSync.reload({stream:true}));
```

**Comment by noahgrant** [comment]
++, might this be related to the Vinyl -> Buffer issue mentioned [https://github.com/floatdrop/gulp-watch/issues/132#issuecomment-76586444](here)

**Comment by floatdrop** [comment]
@siliconalchemy what kind of problem you are having? Some output or examples (and highlighting to issue code) would be great.

**Comment by siliconalchemy** [comment]
@floatdrop, code is quite simple, as above.  I've added a tap to ensure that the compiled html is coming through which it is:
```
[22:09:31] gulp-watch-6rl3iwrk7qq9 saw markup.jade was changed
<File "markup.jade" <Buffer 65 78 74 65 6e 64 73 20 69 6e 63 6c 75 64 65 73 2f 6c 61 79 6f 75 74 0a 0a 62 6c 6f 63 6b 20 74 69 74 6c 65 0a 20 20 20 20 2b 74 69 74 6c 65 28 5b 27 44 ...>>
dist/markup.html
```

**Comment by siliconalchemy** [comment]
If I change the watch line from:
 .pipe(plugins.watch(config.paths.src.jadePath+'/*.jade', {verbose: true}).on('data', function(file){console.log(file);}))
to
 .pipe(plugins.watch(config.paths.src.jadePath+'/*.jade', {verbose: true}))

Then updated files stop being run through jade, ie. the stream 'hangs'.

**Comment by UltCombo** [comment]
Closing this issue as it is very old and inactive. I can use gulp-watch and BrowserSync just fine, so I'm assuming the issue has been fixed at some point.

Please comment/reopen if anyone is still experiencing this issue.
