### ISSUE TITLE
Randomly not passing data in buffer

### ISSUE THREAD

**Issue by siliconalchemy** [floatdrop/gulp-watch#143]
I'm using gulp-watch in a pipe action to compile jade markup, watching either a directory or globbed files, and it randomly fails to pass the necessary changes through to the rest of the pipe, sometimes requiring multiple saves of the changed file to get the required action.

My task starts like this:
```
 gulp.src([config.paths.src.jadePath+'/*.jade', '!'+config.paths.src.jadePath+'/includes/**/*'])
            .pipe(plugins.watch(config.paths.src.jadePath, {verbose: true}).on('data', function(file) console.log(file);}))
            .pipe(plugins.jade({
                pretty: true
            }))
            etc etc
```

Sometimes it's successful:
```
 <File "content/markup/jade/makup.jade" <Buffer 65 78 74 65 6e 64 73 20 69 6e 63 6c 75 64 65 73 2f 6c 61 79 6f 75 74 0a 0a 62 6c 6f 63 6b 20 74 69 74 6c 65 0a 20 20 20 20 2b 74 69 74 6c 65 28 5b 27 50 ...>>
html/content/markup/jade/markup.html
[12:22:29] content/markup/jade/markup.jade was changed
```

Sometimes it's not:
```
 <File "content/markup/jade/markup.jade" <Buffer >>
[12:22:29] 1 error found in src/content/markup/jade/markup.html
[12:22:29] [L1:C1] Doctype must be first. (doctype-first)
```

It looks like gulp-watch recognises the file change but isn't passing anything through to the pipeline, is that right?

**Comment by siliconalchemy** [comment]
Grr, is there any way of turning markdown off in a comment?

**Comment by gustavohenke** [comment]
Format it as code, use triple "`": https://guides.github.com/features/mastering-markdown/

**Comment by siliconalchemy** [comment]
Great, thanks!

**Comment by floatdrop** [comment]
@siliconalchemy could it be, that you are using some very smart IDE that does some file magic? Is this happens with `touch` command from console (because I can't reproduce it unfortunatly)?

**Comment by siliconalchemy** [comment]
Hi @floatdrop, yes possibly - I'm using cloud9 ide over ssh (as in a cloud9 ssh project).

**Comment by floatdrop** [comment]
@siliconalchemy I picking it with Atom, guess `chokidar` picks it before editor is done saving sometimes:

```
change
<File "mobile/app.js" <Buffer 61 61 61 73 64 61 73 64 61 73 0a>>
  watch 51012352 +128ms
change
<File "mobile/app.js" <Buffer >>
  watch 51012352 +122ms
change
<File "mobile/app.js" <Buffer 61 61 61 73 64 61 73 64 61 73 0a>>
  watch 51012352 +108ms
change
```

This is very rare bug thou. One way to solve it - add some time interval, before reading happens. Other - just filter empty files.

**Comment by floatdrop** [comment]
Please update to `4.2` version. If this is still happens, try to increate `readDelay` option.

**Comment by siliconalchemy** [comment]
Upgrading to 4.2 seems to have solved it without any additional readDelay tweaking.  Initial tests show 100% success.  Thanks :)
