### ISSUE TITLE
Callback pattern Vinyl parameter becomes Buffer type at some point during tasks

### ISSUE THREAD

**Issue by noahgrant** [floatdrop/gulp-watch#144]
Using the gulp-watch callback pattern, ie:

```js
watch(<jade templates glob>, function(files) {
  return files.pipe(plumber())
    .pipe(jade())
    .pipe(gulp.dest('./dist/'));
```

fails on every save because at some point the File object becomes just a Buffer Type (seems to be `File.contents`).

putting a console.log(files) before the return statement above yields a File object as we'd expect:
```
<File "filename.jade" <Buffer 65 78 74 65 6e 64 73 20 5f 6c 61 79 6f 75 74 73 2f 73...
```

adding a console.log(file) statement to the beginning of the [gulp-jade index.js file](https://github.com/phated/gulp-jade/blob/108042113374e8310bb98584c18efd4b2757b551/index.js#L15) shows:
```
<Buffer 65 78 74 65 6e 64 73 20 5f 6c 61 79 6f 75 74 73 ...
```

The process then fails because, of course, the Buffer has no `.isStream` or `.isBuffer` methods.

**Comment by noahgrant** [comment]
(also note that attaching `.on(data, function(file) {console.log(file);})` to the [outputStream in gulp-watch index.js](https://github.com/floatdrop/gulp-watch/blob/master/index.js#L55) also yields the File object output listed above.

**Comment by floatdrop** [comment]
@noahgrant looks like you are using old version of `gulp-watch` from the code above. Callback in `4.0` called with Vinyl file object as argument, not a Stream.

**Comment by noahgrant** [comment]
huh...i guess i'm confused then.  I thought [vinyl files](https://github.com/wearefractal/vinyl#file) were typically used with the `contents` property as a stream.  How exactly are you supposed to do an incremental build using the callback pattern now, then?  Can you add an example to the doc readme?

**Comment by floatdrop** [comment]
@noahgrant you can use [this snippet](https://github.com/floatdrop/gulp-watch/tree/master/docs#incremental-build) or wrap callback into [gulp-batch](https://www.npmjs.com/package/gulp-batch) to get stream of files in callback.
