### ISSUE TITLE
handling errors hangs gulp-watch stream

### ISSUE THREAD

**Issue by siliconalchemy** [floatdrop/gulp-watch#145]
I have a simple pipeline:
```
return gulp.src(config.paths.src.jadePath+'/*.jade')
            .pipe(plugins.watch(config.paths.src.jadePath+'/*.jade').on('data', function(file){console.log(file);}))
            .pipe(plugins.jade({ pretty: true }))
            .on('error', function(error) {
                plugins.util.log(plugins.util.colors.red(error.message));
                this.emit('end');
            })
            .pipe(gulp.dest(config.paths.dest.basePath))
```
It works great, and if a single jade file is updated the watcher instantly catches and fires the jade compile and copy to dest.  However, if there is an error that is caught by the on('error'), it outputs the error and then hangs the pipeline.  If you change files it still recognises this but no longer seems to fire the actions in the pipeline.  As an example:
```
<File "markup.jade" <Buffer 65 78 74 65 6e 64 73 20 69 6e 63 6c 75 64 65 73 2f 6c 61 79 6f 75 74 0a 0a 62 6c 6f 63 6b 20 74 69 74 6c 65 0a 20 20 20 20 2b 74 69 74 6c 65 28 5b 27 44 ...>>
<File "markup.jade" <Buffer 65 78 74 65 6e 64 73 20 69 6e 63 6c 75 64 65 73 2f 6c 61 79 6f 75 74 0a 0a 62 6c 6f 63 6b 20 74 69 74 6c 65 0a 20 20 20 20 2b 74 69 74 6c 65 28 5b 27 44 ...>>

[23:44:24] jade/markup.jade:19
Unexpected token else

<File "data-datatables.jade" <Buffer 65 78 74 65 6e 64 73 20 69 6e 63 6c 75 64 65 73 2f 6c 61 79 6f 75 74 0a 0a 62 6c 6f 63 6b 20 74 69 74 6c 65 0a 20 20 20 20 2b 74 69 74 6c 65 28 5b 27 44 ...>>
```
The first markup.jade <Buffer line is a successful update, the second is a deliberate error which outputs an error as expected, then the third is ignored - it doesn't trigger the expected actions in the pipeline, and any further updates are also ignored.  I've also tried plumber, same result.

**Comment by floatdrop** [comment]
This is how `Streams` work in Node. You can use [gulp-plumber](https://github.com/floatdrop/gulp-plumber) to fix this.
