### ISSUE TITLE
Only operate on files changed?

### ISSUE THREAD

**Issue by DelvarWorld** [floatdrop/gulp-watch#146]
If I do this:

    watch(source).pipe(debug()).pipe(gulp.dest(dest));

when I add a file in source, it is output by the debug line, however, the file does not appear in dest. How can I perform an operation on the files changed that come out of watch?

**Comment by harscoet** [comment]
+1

**Comment by DelvarWorld** [comment]
http://blog.andrewray.me/how-to-copy-only-changed-files-with-gulp/ ;)
