### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by entozoon** [floatdrop/gulp-watch#148]
I've recently re-installed this plugin (v4.2.0) and found it no longer works, the watch doesn't trigger.
After some investigating, I've figured out that it has a dependency for 
```
"anymatch": "^1.1.0",
```
which used to load 1.1.0 which worked fine, but now loads 1.2.0, which is like 3 megabytes bigger and stops it all from working.

**Comment by entozoon** [comment]
I like to load gulp-watch using a package.json and npm update and link.. but now I'm not sure how to override this dependency, short of going into the node_modules and cut and pasting things.. which is such a pain.

**Comment by floatdrop** [comment]
@entozoon according anymatch readme, they switched to [micomatch](https://github.com/jonschlinkert/micromatch) inside.

Could you provide more details about gulpfile/OS/how-to-reproduce? I have all tests green in `gulp-watch` (with updated dependencies).

**Comment by entozoon** [comment]
Windows 7 64-bit.
all packages thoroughly updated - npm update and npm link

can I ask why your dependencies aren't fixed versions? it would solve problems like this

**Comment by floatdrop** [comment]
@entozoon seems like micromatch have problems on Windows. Please open issue there.

> can I ask why your dependencies aren't fixed versions? it would solve problems like this 

It is not common practice to lock all dependencies (look at [express for example](https://github.com/strongloop/express/blob/master/package.json#L29-L54)) - patch fixes are important. Besides you can do `npm shrinkwrap` and lock anymatch version.

**Comment by entozoon** [comment]
Any clue as to why it doesn't work anymore though? I've updated my previous comment with as much info as I can
