### ISSUE TITLE
Does not work when using wildcards

### ISSUE THREAD

**Issue by mpiasta-ca** [floatdrop/gulp-watch#150]
Spent over an hour on this already. Finally I just switched to using `gulp.watch(...)` instead and that worked right away.

Created a new build today, installed using `npm install gulp-watch --save-dev`. 

Task was being fired. But the source files look like they're not loading properly.

This doesn't work:
```
var gulp = require('gulp'),
    watch = require('gulp-watch');
gulp.task('watch', function () {
  watch('src/**/*.js', function () {
    console.log("Watch is working...");
  });
});
```

Strangely, using a direct path it works:
```
var gulp = require('gulp'),
    watch = require('gulp-watch');
gulp.task('watch', function () {
  watch('src/scripts/app.js', function () {
    console.log("Watch is working...");
  });
});
```

Couldn't get it to work using wildcards like `src/**/*.js` or even just `src/scripts/*.js`.

**Comment by yumitsu** [comment]
You can turn on verbose option and see if `gulp-watch` handles file changes properly:
```js
watch('src/**/*.js', { verbose: true }, function () {
  ...
}
```

**Comment by allankikkas** [comment]
Just debugged the same issue for couple of hours. Issue happens with updated anymatch module (1.1.0 works, 1.2.* does not). For some reason anymatch went from using minimatch to micromatch and this breaks wildcards usage.

**Comment by floatdrop** [comment]
Try version `4.2.1` (it have fixed `anymatch` version to `1.1.x`). //cc @es128

**Comment by es128** [comment]
There were some updates published last night. Still experiencing these problems with the latest deps? 

//cc @jonschlinkert

**Comment by jonschlinkert** [comment]
I'm here to help if we can nail down something specific.

> For some reason anymatch went from using minimatch to micromatch and this breaks wildcards usage.

hyperbole maybe? jk 

if patterns like `**/*.js` are failing, I'm guessing it's something in the implementation - not pattern matching. either way I want to help.

**Comment by jonschlinkert** [comment]
I'm looking at anymatch and everything related here to see if I can find something too.

**Comment by jonschlinkert** [comment]
@es128 was [this commit](https://github.com/paulmillr/chokidar/commit/44725ca4a8a403942c9e3c2ac87ffbb1c373fda7) part of the bump in gulp-watch?

**Comment by es128** [comment]
@jonschlinkert just to answer your question about that commit - no, it hasn't been published yet. Been trying to tie up loose ends and get chokidar 1.0.0-rc5 out the door (which should be the last rc, intend to cut 1.0.0 after about another week)

**Comment by mpiasta-ca** [comment]
Downloaded `gulp-watch` today and looks like it's working.

**Comment by es128** [comment]
Well the recent version of `gulp-watch` actually just locks down the version of `anymatch`. @jonschlinkert and I have been working out some issues (mostly windows based) we discovered today after this issue was posted. Should be in good shape very soon to be able to go back to using latest.

I apologize for the impact this has had on anyone's time.

**Comment by floatdrop** [comment]
@es128 thanks for sorting this out. Watching fs is hard, so just tell when it is time to unlock. :+1:

**Comment by jonschlinkert** [comment]
that's awesome, thank you @floatdrop.  

and I also want to echo @es128's sentiments, really sorry about this impacting people's time.

**Comment by es128** [comment]
@floatdrop regarding when it's time to unlock the version, we've resolved the issue described in this thread I think, but you could probably wait until the two currently open ones get fixed: https://github.com/jonschlinkert/micromatch/issues/19 & https://github.com/jonschlinkert/micromatch/issues/20.

**Comment by floatdrop** [comment]
@es128 will be watching on them.

**Comment by jonschlinkert** [comment]
yes, good advice. taking care of some stuff to pay the bills, but this is top of my list
