### ISSUE TITLE
Unlink events without unlinking files

### ISSUE THREAD

**Issue by laurelnaiad** [floatdrop/gulp-watch#151]
It seems a recent change has a series of unlink events bubbling up without changes to file.

I am investigating whether it's something in my code that is touching them, but so far I'm not aware of it. 

This has been reported under RHEL and OSX.

**Comment by laurelnaiad** [comment]
Update seems like the option ignoreInitial option is being passed successfully to chokidar, looking into what may have changed in chokidar now....

**Comment by wolverian** [comment]
I'm seeing this as well under Ubuntu 14.04, but not under OS X.

**Comment by wolverian** [comment]
I see this only on 4.2.2. The issue does *not* happen with 4.2.1.

**Comment by floatdrop** [comment]
> I'm seeing this as well under Ubuntu 14.04, but not under OS X.

I guess problem somewhere near watcher then.

> I see this only on 4.2.2. The issue does not happen with 4.2.1.

Could you provide verbose output?

//cc @UltCombo

**Comment by UltCombo** [comment]
The only change between 4.2.1 and 4.2.2 was fixing a bug with the emitted vinyl file's `path` for `unlink` events, which was not always an absolute path.

@wolverian @laurelnaiad I can investigate if you provide a gulpfile and some more info, steps to reproduce, expected and actual behavior.

**Comment by wolverian** [comment]
I can't reproduce this with 4.2.3 anymore.

**Comment by UltCombo** [comment]
It was most likely a bug with Chokidar then, as the only change between 4.2.2 and 4.2.3 was bumping the Chokidar dependency.
