### ISSUE TITLE
`file.path` is not absolute when file.event === 'unlink'

### ISSUE THREAD

**Issue by UltCombo** [floatdrop/gulp-watch#152]
Vinyl files' [`path` property](https://github.com/wearefractal/vinyl#optionspath) should be the full path to the file.
The handling for add/change seems correct, the problem is with unlink.

**Comment by UltCombo** [comment]
Looks like gulp-watch passes [chokidar's filepath](https://github.com/floatdrop/gulp-watch/blob/ce44f3918839886da315fd3984a945ac8e21eebb/index.js#L60) to the [callback](https://github.com/floatdrop/gulp-watch/blob/master/index.js#L73) for `unlink` events, while add/change events have the filepath set by [`vinyl.read`](https://github.com/floatdrop/gulp-watch/blob/master/index.js#L78) -- `vinyl.read` ignores the `path` option and sets its own (which is the correct one in this case).

**Comment by UltCombo** [comment]
I was having a hard time to reproduce the issue in the unit tests, until I realized gulp-watch's unit tests [pass absolute paths to chokidar](https://github.com/floatdrop/gulp-watch/blob/ce44f3918839886da315fd3984a945ac8e21eebb/test/callback.js#L11), that is why the paths reported by chokidar are always absolute in the unit tests.

**Comment by floatdrop** [comment]
Thanks for digging it out! Very nice catch!
