### ISSUE TITLE
watching with glob pattern (eg **/*.ext) does not work with windows junction point

### ISSUE THREAD

**Issue by dragonflypl** [floatdrop/gulp-watch#160]
Hi,

is is a bug / not supported or i'm not configuring gulp-watch properly?

Thanks!

**Comment by mhoyer** [comment]
@dragonflypl, I can verify this issue as well. I guess it's related to [chokidar](https://github.com/paulmillr/chokidar) - *maybe*?

**Comment by dragonflypl** [comment]
I was debugging it and created a workaround but I honestly don't remember who was the culprit.

**Comment by UltCombo** [comment]
Closing as old inactive issue. Please comment or reopen if you still experience this issue.
