### ISSUE TITLE
chokidar events

### ISSUE THREAD

**Issue by movie4** [floatdrop/gulp-watch#161]
Hello!

How i can use more ``chokidar`` events? 
Like:

    .on('add', function(path) { console.log('File', path, 'has been added'); })
    .on('change', function(path) { console.log('File', path, 'has been changed'); })
    .on('unlink', function(path) { console.log('File', path, 'has been removed'); })
    .on('addDir', function(path) { console.log('Directory', path, 'has been added'); })
    .on('unlinkDir', function(path) { console.log('Directory', path, 'has been removed'); })
    .on('error', function(error) { console.log('Error happened', error); })
    .on('ready', function() { console.log('Initial scan complete. Ready for changes.'); })

Now working: ``error`` and ``ready`` events

**Comment by floatdrop** [comment]
I think there is no way atm.

**Comment by movie4** [comment]
thanks!
