### ISSUE TITLE
Doesn't work after watched directory was removed

### ISSUE THREAD

**Issue by fedotxxl** [floatdrop/gulp-watch#162]
Hello

I watch for changes of source files / clean target folder by `rimraf` / compile source and copy them to target folder / watch for changes in target folder to trigger `browser-sync`. The final part doesn't work after first cycle - after `rimraf` cleans  target folder watch doesn't work anymore.

I use following configuration to clean target folder:

    return gulp.src('./build', {read: false})
        .pipe(rimraf({force: true}));

Ubuntu 14.04

**Comment by floatdrop** [comment]
@fedotxxl is placing `console.log('debug');` before `return` printing every time you change watched files?

**Comment by fedotxxl** [comment]
I found the reason of the problem: I watch files by following rule `./build/**`. If I configure rimraf to delete directory ('./build' as src) it will break watch. If I configure rimraf to delete all files in build directory (`./build/**/*.*` as src) it will **not** break watch.

Is it ok?

**Comment by floatdrop** [comment]
I guess it is ok at some level, because chokidar attaches something like `fs.watch` on `inode` of directory - and when you recreate it, it have new `inode`. If you can avoid this situation - please do.
