### ISSUE TITLE
Gulp watch is failed to detect file changes on a mounted drive

### ISSUE THREAD

**Issue by rbhalla** [floatdrop/gulp-watch#163]
Right now I'm using a vagrant box to host my environment locally and using shared folders to allow the VM access to app files.

I'm currently using gulp to monitor all file changes, asset and app files. When an app file changes I reload my node server. This unfortunately requires me to run gulp from inside the VM which is when everything fails.

I think this is a problem regarding fs watch and was wondering if it's possible to include an option to use polling as a fallback?

**Comment by floatdrop** [comment]
Yep, skim through [chokidar options](https://github.com/paulmillr/chokidar#performance).

**Comment by rbhalla** [comment]
Ahh sorry I missed the bit in the readme where options were passed straight to chokidar. Thanks.
