### ISSUE TITLE
Incremental build watcher doesn't seem to be rebuilding

### ISSUE THREAD

**Issue by rbhalla** [floatdrop/gulp-watch#164]
Right now my task is fairly vanilla:

```
gulp.task('js', function() {
    return gulp.src('./assets/js/*.js')
        .pipe(watch('./assets/js/*.js', watchOptions))
        .pipe(plumber())
        .pipe(concat('main.js'))
        .pipe(gulp.dest('./public/js'));
});
```

where `watchOptions` is
```
var watchOptions = {
    usePolling: true, // Needed for mounted drives
    verbose: true
};
```

Since I have verbose turned on, when I make a change I can see gulp output that the file has changed, except the output file doesn't seem to update. When I rerun the task, though, the output file does update correctly.

I've been trying all sort of combinations for a while now and can't seem to see why it's not working considering it seems like it works for a lot of examples out there.

Can anyone shed any light on this?

**Comment by floatdrop** [comment]
`gulp-watch` in stream mode is never emits `end` - but `gulp-concat` is waiting for this event. Use callback mode with `gulp-concat`.

**Comment by daredevil82** [comment]
Can you include a callback example for use with `gulp-concat`?  Google searches show no usable results on this point.

**Comment by floatdrop** [comment]
@daredevil82 it depends, but something like this will work:

```js
gulp.task('callback', function (cb) {
    watch('css/**/*.css', function () {
        gulp.src('css/**/*.css')
            .pipe(concat('css/**/*.css'))
            .on('end', cb);
    });
});
```

**Comment by daredevil82** [comment]
That did it, thanks.

**Comment by daredevil82** [comment]
For a gulp task watch setup following your recommendation:

    gulp.task("watch", ["js-concat", "compass-watch"]);

    gulp.task("js-concat", function(cb){
      watch(jsSrcPath, function(){
        gulp.src(appFileOrder)
            .pipe(plumber())
            .pipe(annotate())
            .pipe(concat("all.js"))
            .pipe(gulp.dest(jsDistPath))
            .pipe(uglify())
            .pipe(rename({extname: ".min.js"}))
            .pipe(gulp.dest(jsDistPath))
            .on("end", cb);
      });
    });

The following continually shows in the console after the first time `watch` executes:

    [16:40:34] 'js-concat' errored after 34 s
    [16:40:34] Error: task completion callback called too many times
    at finish   (/Users/jasonjohns/projects/python/mileagetracker/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:15:10)
    at DestroyableTransform.cb (/Users/jasonjohns/projects/python/mileagetracker/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at DestroyableTransform.emit (events.js:129:20)
    at /Users/jasonjohns/projects/python/mileagetracker/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)

I'm not sure if this is a direct result of `gulp-watch` or `gulp-concat`.  Do you have any idea how to alleviate this?
