### ISSUE TITLE
Silent failure if target directory does not exist

### ISSUE THREAD

**Issue by foxx** [floatdrop/gulp-watch#165]
Take the following example;

```
watch('./somedir/**.*')
```

In the scenario where `./somedir` is created AFTER the watch has been started, subsequent events are not detected, and no error is thrown to say the target path doesn't exist. 

Surely at the very least, an error should be thrown or a warning displayed? Ideally it should detect these situations and deal with them properly though.

**Comment by floatdrop** [comment]
I think it should be handled in [chokidar](https://github.com/paulmillr/chokidar), not here.
