### ISSUE TITLE
implement watch.listen()?

### ISSUE THREAD

**Issue by MystK** [floatdrop/gulp-watch#167]
I really like gulp-watch, and something I feel that would be useful to add is a watch.listen(), which would work the same way as gulp-livereload's. gulp.livereload won't reload the page unless livereload.listen() was ran first. 

This is useful because I would be able to leave the watch pipe in there, and it would only activate if I also added the task, "watchStart" or something.

Here is some sample use code from the gulp-livereload readme.

```javascript
gulp.task('less', function() {
  gulp.src('less/*.less')
    .pipe(less())
    .pipe(gulp.dest('css'))
    .pipe(livereload());
});
 
gulp.task('watch', function() {
  livereload.listen();
  gulp.watch('less/*.less', ['less']);
});
```

the livereload function would only work if it was "gulp watch less." "gulp less" would not cause the livereload behavior.

I think it could be implemented without any breaking changes, by having a {start: true} the default option when requiring the plugin, and one would manually have to set start to false to use the feature.

What do you guys think? Is this a good idea?

**Comment by floatdrop** [comment]
I don't think that should be fixed in `gulp-watch`. May be move `livereload.listen()` out of `watch` task?...
