### ISSUE TITLE
Default base not the same between gulp.src and gulp-watch

### ISSUE THREAD

**Issue by pauldijou** [floatdrop/gulp-watch#171]
I hope I will not say something wrong since I'm not totally sure of it but it looks like default bases on `gulp.src` and `gulp-watch` are not consistent. The first one is relative to the start of the glob whereas the second one is relative to the root of the project when using relative paths. Let's consider the following code:

```js
gulp.task('babel', ['clean:scripts'], function () {
  return gulp.src('./scripts/**/*.js')
    .pipe($.watch('./scripts/**/*.js'))
    .pipe($.babel(config))
    .pipe(gulp.dest('build'));
});
```

Pretty simple, the goal is to compile all files once and then do an incremental build. So when running a first time, through `gulp.src`, we will have something lile:

```
{
  filename: '/whatever/projects/tmp/scripts/app.js',
  filenameRelative: 'app.js'
}
```

But if saving the `app.js`, it will go through `gulp-watch` and here is the new relative path:

```
{
  filename: '/whatever/projects/tmp/scripts/app.js',
  filenameRelative: 'scripts/app.js'
}
```

Of course, because of that, it doesn't save the resulting file at the same place inside the `build` folder (which is sad). It's worth mentioning that if you replace `./scripts/**/*.js` with `scripts/**/*.js`, everything works as expected (`filenameRelative: 'app.js'`).

I don't really know why this `./` break something inside `gulp-watch`...

**Comment by chrahunt** [comment]
I ran into the same issue. Removing the leading `./` fixed the problem, as you said.

```javascript
var dir = "./build/dev";
// Files get initially put into dev directly, but on change they are moved into dev/src
var badFileSets = [
    // Asset files in src
    ['./src/**/*', '!./src/js/**/*'],
    // Asset files in vendor
    ['./vendor/**/*', '!./vendor/js/**/*']
];
// Files move as expected initially and when changed.
var fileSets = [
    // Asset files in src
    ['src/**/*', '!src/js/**/*'],
    // Asset files in vendor
    ['vendor/**/*', '!vendor/js/**/*']
];
fileSets.forEach(function(fileSet) {
    gulp.src(fileSet)
        .pipe(watch(fileSet))
        .pipe(plumber())
        .pipe(gulp.dest(dir));
});
```

**Comment by lucasmotta** [comment]
I had the same issue as described above. If you remote the leading `./` from your source files, the files are compiled to the correct location.
