### ISSUE TITLE
Watch doesn't fire if running task from Windows VM if code is edited on host.

### ISSUE THREAD

**Issue by trevcor** [floatdrop/gulp-watch#174]
I'm running my gulp tasks in a parallels Windows 7 since that is where my localhost is running.  I have a drive shared with my host Mac that contains my workspace.  Normally I use sublime on my mac as a text editor.  For some reason when I make a code change from the mac the watch never fires on the host machine.  It only works if I make changes from an editor on the windows VM.

I just setup a simple task to run jslint on any file change to test with.

gulpfile.js
    var gulp = require('gulp');

    var jshint = require('gulp-jshint');
    var stylish = require('jshint-stylish');
    var gulpWatch = require('gulp-watch');
    gulp.task('lint', function() {
      return gulp.src(['WebContent/**/*.js', '!WebContent/libraries/**/*.js'])
        .pipe(jshint())
        .pipe(jshint.reporter(stylish));
    });
    gulp.task('dev', function() {
	    return gulpWatch('WebContent/*.js', function(){
		     gulp.start('lint');
	    });
    });

Am I doing something wrong or is this a bug?  I've used the same setup for awhile with Grunt without any issues.

**Comment by HeyImAlex** [comment]
Have you tried passing `{ usePolling: true }`?

**Comment by UltCombo** [comment]
Shared folders across host and VMs are a pain in the arse for file system watchers, but enabling polling mode usually fixes the issue. Try setting the `usePolling: true` option as Alex mentioned, and check out the other [polling-specific settings](https://github.com/paulmillr/chokidar#performance) if you experience high CPU/disk usage.
