### ISSUE TITLE
Unexpected watch event trigger

### ISSUE THREAD

**Issue by zjuasmn** [floatdrop/gulp-watch#181]
Hi, I like this plugin very much and I use it in my development. But I found that when some files ware edited, some other unrelated files would trigger a change event.  That is weird.

For example, when I edit `src/t/a.md`, your plugin would tell me that `src/thirdParty.styl` has been change. And my gulpfile.js is as follows:

```js
var gulp = require('gulp');
var watch = require('gulp-watch');

gulp.task('default', function(){
    watch("src/thirdParty.styl", function(vinyl){
        console.log(vinyl, vinyl.event);
    });
});
```

I make a repository to reappear this issue. Looking forward to your response. Thank you.
https://github.com/zjuasmn/gulp-watch-error-test

My environment is Win7+node#0.10.38+gulp#3.9.0+gulp-watch#4.2.4

**Comment by floatdrop** [comment]
@zjuasmn thanks for the repo! But unfortunatly I can't reproduce it on OSX. Could you try `4.2.5` version of `gulp-watch`?

**Comment by zjuasmn** [comment]
@floatdrop The issue still exists in 4.2.5. And I found that it might comes from chokidar. https://github.com/paulmillr/chokidar/issues/296

**Comment by senritsu** [comment]
Added an update with more information on the circumstances under which the bug appears to the chokidar issue at https://github.com/paulmillr/chokidar/issues/296
