### ISSUE TITLE
Gulp Watch with Dependencies and Callback

### ISSUE THREAD

**Issue by chris-carrington** [floatdrop/gulp-watch#184]
My issue is basically trying to do exactly what this poster was attempting 5 months ago. <a href="http://stackoverflow.com/questions/28333556/gulp-watch-with-dependencies-and-callback" target="_blank">Click Here</a> 

I would like to 
*   Trigger a task to run in the callback of a watch
*   Call the watch callback after the run callback is completed

This is my current implementation which requires the deprecated `gulp.run()` to perform as intended. It's a live reload implementation where I only want to notify a live reload after the task is run in the watch callback.

````
npm.gulp.task('default', ['unit-tests', 'css-compile', 'copy-assets', 'index', 'server'], function()
{
   function initializeWatch(stream, todo)
   {
      npm.gulp.watch(stream, function(vinyl)
      {
         npm.gulp.run(todo, function()
         {
            var fileName = npm.path.relative(dir.buildDirectory, vinyl.path);
            server.liveReload.changed({ body: {files: [fileName]} });
         });
      });
   }

   initializeWatch(dir.appAndCommonJsList, 'unit-tests');
   initializeWatch(dir.appAndCommonLessList, 'css-compile');
   initializeWatch(dir.appAndCommonJadeList, 'index');
   initializeWatch(dir.imgSrcDirectory, 'copy-assets');
   initializeWatch(dir.jsonSrcDirectory, 'copy-assets');
});
````

**Comment by floatdrop** [comment]
Please, ask such questions at [stackoverflow](http://stackoverflow.com/search?q=gulp&s=937d0338-cf13-4ee6-87d5-d6a0213745c4).
