### ISSUE TITLE
`cwd` not working since 4.3

### ISSUE THREAD

**Issue by julien-f** [floatdrop/gulp-watch#185]
## Set up

`gulpfile.js`:

```js
var gulp = require('gulp')
var watch = require('gulp-watch')

gulp.task('default', function () {
  return watch('**/bar.js', {
    base: __dirname + '/foo',
    cwd: __dirname + '/foo',
    ignoreInitial: false,
    verbose: true
  })
})
```

Files:

- `foo/`
    - `bar.js`
- `bar.js`
- `gulpfile.js`

## Expected

> As obtained with gulp-watch < 4.3.

```
> gulp
[13:21:30] Using gulpfile /tmp/gulpfile.js
[13:21:30] Starting 'default'...
[13:21:30] bar.js was added
```

## Actual

```
[13:21:37] Using gulpfile /tmp/gulpfile.js
[13:21:37] Starting 'default'...
[13:21:37] ../bar.js was added
[13:21:37] bar.js was added
```

> Note the incorrect presence of `../bar.js`!

**Comment by floatdrop** [comment]
`base` and `cwd` are options for vinyl objects and actual behaviour is expected tbh. 

 * `foo/bar.js` <->  `bar.js` in output
 * `bar.js` <->  `../bar.js` in output

**Comment by julien-f** [comment]
`cwd` is used by both `gulp.src()` and previous versions of `gulpWatch()` (via chokidar) to determine from where relative paths should be resolved.

Therefore, `bar.js` should not be matched by `**/bar.js` if cwd is `__dirname/foo` and that is exactly `gulp.src()` behaviour.

**Comment by floatdrop** [comment]
@julien-f okay, now I get it. Can you try `4.3.2`?

**Comment by julien-f** [comment]
Successfully tested from the git repository (as 4.3.2 is not published yet).

**Comment by floatdrop** [comment]
@julien-f thanks! (published it)
