### ISSUE TITLE
Is there any options to exclude paths from watching?

### ISSUE THREAD

**Issue by zhekaus** [floatdrop/gulp-watch#186]
Is there any options to exclude paths from watching?
As I see, the familiar way I used to doesn’t work here:
  watch(['./app/js/*.js', '!./app/js/templates.js'], function (vinyl) {
    gutil.log(vinyl.event + ': ' + vinyl.path);
  });

**Comment by floatdrop** [comment]
@zhekaus this was a bug. Update please.
