### ISSUE TITLE
Read False Still Valid?

### ISSUE THREAD

**Issue by pixelshaded** [floatdrop/gulp-watch#189]
In the docs it says to use read: false in the options config if you don't want to read files. I've looked in the chokidar docs and there is no mention of this option. I've looked in gulp-watch source and I am not seeing this option being used either.

I have some watchers that detect a large numbers of file changes (500+) and it's completely crippling my tasks. I get the impression that this is because its reading those files (when using gulp.watch which doesn't read files, everything runs smoothly).

Is read false still used / relevant?

**Comment by floatdrop** [comment]
Yes, it should be - `read` option passed to [vinyl-file](https://www.npmjs.com/package/vinyl-file).

**Comment by pixelshaded** [comment]
```
vinyl.read(filepath, opts, write.bind(null, event));
```
Alright I see it now. Thanks. Must be something else then that's slowing everything down.
