### ISSUE TITLE
Watch outside folder

### ISSUE THREAD

**Issue by dkulakov** [floatdrop/gulp-watch#190]
Hello, if I have a structure in project

<pre>
<code>
- project
-- scss
--- file.scss (this file has @import ../../lib/different/file.scss)
-- gulpfile.js
-- css
- lib
-- different
--- different.scss
</code>
</pre>

gulpfile.js

<pre>
<code>
var gulp = require('gulp'),
	sass = require('gulp-sass'),
	watch = require('gulp-watch');

gulp.task('sass', function () {
	gulp.src('scss/**/*.scss')
		//Need for rebuild only files that change
		.pipe(watch('scss/**/*.scss'))
		.pipe(sass())
		.pipe(gulp.dest('css'));
});
</code>
</pre>

How should I adjust options or watcher in command for monitoring modification in lib/different/different.scss file? So, if I make changes in different.scss than file.scss will be recompiled.

**Comment by floatdrop** [comment]
`gulp-watch` is not parsing files for imports. Either by hands or with some other plugins.
