### ISSUE TITLE
Request debounce feature

### ISSUE THREAD

**Issue by NgYueHong** [floatdrop/gulp-watch#191]
On certain event, there will be more than one files changes such as on git branch switching. This result in a repeatedly running of task and causes performance & stability issue.

It would be great if gulp-watch can come with the "debounce" feature. Meaning, when there is more than one file changes in the very short period in the watch folder, gulp-watch will only execute the task once.

**Comment by floatdrop** [comment]
Use [gulp-batch](https://github.com/floatdrop/gulp-batch) for those cases - https://github.com/floatdrop/gulp-watch/tree/master/docs#starting-tasks-on-events
