### ISSUE TITLE
Issue with OR syntax on Windows

### ISSUE THREAD

**Issue by jleck** [floatdrop/gulp-watch#192]
Hi,

I am watching a directory using the following:

`resources/{react,views}/**/*.{js,jsx}`

This works fine on all platforms but Windows where it doesn't pick up changes. Removal of the {} syntax makes it work. We have also converted to gulp.watch command and this works fine.

**Comment by jonschlinkert** [comment]
hmm, when you remove the `{}` syntax, what pattern did you use to get it working? I'm guessing you split that into an array? I'm curious b/c there are a couple of issues that both have brace patterns in them and have similar resulting behavior when the pattern is made more/less explicit.  

this might be an easy fix, like just changing a setting...

**Comment by jleck** [comment]
We tried splitting it into in array but that didn't work for us either. The fix was to change the code to use gulp.watch when on windows. Then we could keep the pattern the same (i.e. with the brackets).

**Comment by UltCombo** [comment]
Looks like this issue has been fixed upstream, the problem is no longer reproducible in the latest version testing in Windows 10.
