### ISSUE TITLE
watch('**/*.js') doesn't works like gulp

### ISSUE THREAD

**Issue by rafaelsq** [floatdrop/gulp-watch#194]
it doesn't trigger events for files matched by glob/pattern like gulp.

Files structure:
```
./assets/es6/main.js
./assets/es6/utils/utils.js
```

working
```JAVASCRIPT
gulp.watch('assets/es6/**/*.js', ['es6']);
gulp.src('assets/es6/**/*.js').pipe(print()); 

// both cases will work just fine and print main.js and utils.js
```

not working
```JAVASCRIPT
// it will trigger only for utils.js
gulpWatch('assets/es6/**/*.js');

// I've found this workaround.
gulpWatch('assets/es6/{,**/}*.js');
```

**Comment by jonschlinkert** [comment]
hmm, strange. I'll take a look at this today to see if I can reproduce, and if so find out if it's a matching issue or a combination of path-rewriting and matching...

**Comment by JMBattista** [comment]
I wanted to chime in that I'm seeing a similar issue. Everything will work fine at first, then at some point in the course of development the js:watch below will break, but the html:watch will keep working fine. The js:watch will keep working for files at src/client/app/foo/*.js but src/client/app/foo/BAR/*.js stops working.



gulp.task('js-dev', function () {
    var ts = config.filter.ts();

    return gulp.src(config.source)
        .pipe(sourcemaps.init())
        .pipe(plumber())
        .pipe(ts)
            .pipe(tsc(tsProject))
        .pipe(ts.restore)
        .pipe(babel())
        .pipe(ngAnnotate())
        .pipe(concat('app.js'))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest(config.dest + 'js/'))
        .pipe(livereload());
});

gulp.task('js:watch', ['js-dev'], function () {
    livereload.listen();
    watch(config.source, function() {
        gulp.start('js-dev')
    });
});


gulp.task('html:partials', function () {
    return gulp.src(config.html)
        .pipe(templateCache(config.templateCache.file, config.templateCache.options))
        // .pipe(minifyHTML({empty:true}))
        .pipe(gulp.dest(config.dest + 'js/'))
        .pipe(livereload());
});

gulp.task('html:watch', ['html'], function () {
    livereload.listen();
    watch(config.html, function() {
        gulp.start('html:partials');
    });
    watch([config.index, config.bower.source, config.bower.style], function() {
        gulp.start('html:index')
    });
});

**Comment by mathiasvalentin** [comment]
I'm experiencing the same issue. A quickfix was to remove the extension.  
```javascript
gulp.watch('assets/es6/**/*');
```

**Comment by Industrial** [comment]
+1

**Comment by tregusti** [comment]
:+1:

**Comment by adambuczynski** [comment]
Having the same issue here, but *only* on windows. On Mac OS X, the patterns with `**/*.js` seem to work fine.

**Comment by UltCombo** [comment]
If anyone can share a sample repository that displays this issue, I'd be happy to test. Last time I checked, `**/*.js` works great in all OS's.

**Comment by adambuczynski** [comment]
You can check this repo, which should display the behaviour: https://github.com/meanie/angular-seed

Changes made to files in the `app` folder to JS files were not being detected in Windows.

The relevant task file is `build/tasks/watch-app-js.js`. The files being watched are defined in `build/config.js`, which are currently: `['app/**/*.js', 'app/components/**/*.html']`. This didn't work. Changing it to `['app/**/*']` fixed it, no other changes were made.

**Comment by adambuczynski** [comment]
Sorry, I think this repo doesn't use `gulp-watch` at all, but instead uses gulp 4's internal watch. The two are probably not related.

**Comment by UltCombo** [comment]
Thanks for reporting back, @adambuczynski.
Both gulp 4 and gulp-watch use the same underlying file system watching package (chokidar). Theoretically, both projects should be affected by it.

I'm not sure what could be causing it, but here is a shot in the dark: are you using npm@3? If so, npm@3's maximally flat dependencies tree may be giving you an outdated chokidar version—can you check the `version` in `node_modules/chokidar/package.json`?

**Comment by jonschlinkert** [comment]
I forgot to come back and mention this a while back, but I spent quite a bit of time trying to reproduce this on windows and mac with no luck. It would be great to figure out what's causing this - if if's still happening.

**Comment by rafaelsq** [comment]
tried it again on mac/ubuntu and seems to be fixed. Thanks!
