### ISSUE TITLE
watch('**') or watch('**/*') should always notify

### ISSUE THREAD

**Issue by andig** [floatdrop/gulp-watch#197]
I'm confused as to what it takes to make watch simply trigger on all files in the pipe, neither of this works:

		gulp.task('watch', function() {
			// watch for JS changes
			gulp.src([
				'gulpfile.js',
				base + 'javascripts/**/*.js'
				// ,
				// '!**/*.min.js',							// omit minified files
			], { read: false })
				.pipe($.watch('**/*')) // '**', '**/*.*'
				.pipe($.jshint())
				.pipe($.jshint.reporter('default'))
				.pipe($.jshint.reporter('fail'));
		});

This in on Windows. Only way I could get it working was by re-pasting the `.src()` spec as the `gulp-watch` examples show. Is this really necessary?

**Comment by floatdrop** [comment]
Use [`ignoreInitial: false`](https://github.com/floatdrop/gulp-watch#optionsignoreinitial) option.

**Comment by andig** [comment]
Much appreciated. Users of gulp-watch like me may not be node experts and use it for their build env only. It would be helpful if the readme contained a short explanaition of what using the chikidar add events actually means.

**Comment by andig** [comment]
I've just tried with `{ ignoreInitial: false }` - doesn't work, neither with `**` nor with `**/*` as pattern. Any thoughts?

**Comment by floatdrop** [comment]
@andig maybe try `./**` or `./**/*.js`? It could be problem with patterns on windows thou.

**Comment by andig** [comment]
Neither is working in my tests. A simple

    var glob = require("glob");

    glob("**/*", {}, function (er, files) {
        console.log(files);
    });

is returning all files though. I'm entirely confused now...

**Comment by floatdrop** [comment]
Hm... Last you can try `4.2.5` version and if it does not work for you - you can use bundled [`gulp.watch`](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb) I guess.
