### ISSUE TITLE
Any plan to add patterns similar to gulp.watch ?

### ISSUE THREAD

**Issue by Qt-dev** [floatdrop/gulp-watch#198]
Hey there,

I was using gulp.watch, from the [gulp API](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb) but ended up having  to switch to gulp-watch.
Now what I found strange is that, to trigger a task on a watch, you have to use the ```gulp.start``` function, [that is pretty "not recommended"](https://github.com/gulpjs/gulp/issues/426)

Is there any plan to get something in the likes of 
```gulp.watch(glob, [tasks], cb)``` ?

**Comment by floatdrop** [comment]
@Qt-dev I don't see any other way to start task in gulp besides `gulp.start`, so either it will be in plugin code or in gulpfile. Neither is recommended.

After [this issue](https://github.com/gulpjs/gulp/issues/1247) is resolved gulp-watch will be deprecated. I can't find new API thou, may be they keep `[tasks]`, may be not.
