### ISSUE TITLE
How to batch changes with gulp 4

### ISSUE THREAD

**Issue by ocombe** [floatdrop/gulp-watch#200]
Hello,

the doc says that if I want to trigger the watch callback only once when multiple files have changed, I should use gulp.batch like this:
```js
gulp.task('watch', function () {
    watch('**/*.js', batch(function (events, done) {
        gulp.start('build', done);
    }));
});
```

But since gulp.start is deprecated in gulp 4, how should I do that ?
I tried this:
```js
gulp.watch('**/*.js', batch(function (events, done) {
    return gulp.series(build)(done);
}));
```

It works, but then when I end the task (with CMD + C), I get the message:
```sh
[09:30:37] The following tasks did not complete: <anonymous>, <anonymous>
[09:30:37] Did you forget to signal async completion?
```
With one `<anonymous>` per execution of the watch.

So, is there a better way than using batch ? If not, what would be the correct syntax ?

**Comment by floatdrop** [comment]
In gulp@4 you should use bundled watcher, since they migrated to `chokidar`.

**Comment by ocombe** [comment]
So you're saying that I should open the issue in the gulp repo, or that it's not a problem anymore ?

**Comment by floatdrop** [comment]
@ocombe yep. I don't sure, but in bundled watcher they could have a solution for this.

**Comment by ocombe** [comment]
Well I haven't found it, but I'll open the issue there. Thanks anyway.
