### ISSUE TITLE
Not watching after symlinks

### ISSUE THREAD

**Issue by Vinorcola** [floatdrop/gulp-watch#204]
Hi all,

Apparently, gulp-watch is not watching files under a symlinks. I have the following architecture:

    Server/
        gulpfile.js
        package.json
        client/  -> ../Client
    
    Client/
        src/

If I put in my gulpfile the following code, it doesn't work:

    gulp.task('watch-client', function()
    {
        watch('client/src/**/*.js', function()
        {
            gulp.start('build-client')
        })
    })

But if I change to the following code, then it work well:

    gulp.task('watch-client', function()
    {
        watch('../Client/src/**/*.js', function()
        {
            gulp.start('build-client')
        })
    })

This is anoying since the Client project folder is not necessary in the same folder than the Server project... Is there a way to make watch work across symlinks?

Thanks.

**Comment by floatdrop** [comment]
Try to pass [`followSymlinks` chokidar option](https://github.com/paulmillr/chokidar#path-filtering).
