### ISSUE TITLE
Watch doesn't see changes

### ISSUE THREAD

**Issue by Lehakos** [floatdrop/gulp-watch#210]
Hello. This is my code:
var
    gulp = require('gulp'),
    sass = require('gulp-sass'),
    prefix = require('gulp-autoprefixer'),
    rename = require("gulp-rename"),
    minifyCss = require('gulp-minify-css'),
    watch = require('gulp-watch');

gulp.task('styles', function() {
  return gulp.src('local/templates/formom/scss/main.scss')
    .pipe(sass()
      .on('error', sass.logError))
    .pipe(prefix("last 2 version", "> 1%", "ie 9", "ie 8"))
    .pipe(minifyCss())
    .pipe(rename('article.min.css'))
    .pipe(gulp.dest('local/templates/formom/css'));
});

//Watch task
gulp.task('watch', function() {
  watch('local/templates/formom/scss/**/*.scss', ['styles']);
});

gulp.task('default', ['watch']);

Why Watch doesn't triggered when i change main.scss?

**Comment by UltCombo** [comment]
Your glob pattern (`local/templates/formom/scss/*/.scss`) seems wrong.

To watch all `.scss` files that are directly inside the scss, try:

```js
watch('local/templates/formom/scss/*.scss', ['styles']);
```

To watch `.scss` files inside the scss directory including subdirectories, try:

```js
watch('local/templates/formom/scss/**/*.scss', ['styles']);
```

Please reopen if you are still facing issues. :wink:

**Comment by UltCombo** [comment]
One more thing, I believe passing an array of task names is not supported. I believe this may work better:

```js
function styles() {
  return gulp.src('local/templates/formom/scss/main.scss')
    .pipe(sass()
      .on('error', sass.logError))
    .pipe(prefix("last 2 version", "> 1%", "ie 9", "ie 8"))
    .pipe(minifyCss())
    .pipe(rename('article.min.css'))
    .pipe(gulp.dest('local/templates/formom/css'));
}

gulp.task('styles', styles);

//Watch task
gulp.task('watch', styles);

gulp.task('default', ['watch']);
```

**Comment by Lehakos** [comment]
It's still doesn't work :(

**Comment by Lehakos** [comment]
Task 'styles' work perfectly, but watch doesn't

**Comment by UltCombo** [comment]
Did you try my last suggestion [above](https://github.com/floatdrop/gulp-watch/issues/210#issuecomment-157014903)? There was a small issue in it, I edited the watch task:

```js
gulp.task('watch', function() {
  watch('local/templates/formom/scss/**/*.scss', styles);
});
```

**Comment by Lehakos** [comment]
Yeh. I did exactly

**Comment by UltCombo** [comment]
It doesn't work even with the [updated watch task](https://github.com/floatdrop/gulp-watch/issues/210#issuecomment-157016197)? That seems odd, I can't spot anything else wrong right now.

**Comment by jzvelc** [comment]
@Lehakos You are probably using Vagrant / Docker / VM with synced filesystem. FSEvents are unavailable and you should be using pooling. Try passing `usePolling` option as stated in [chokidar docs](https://github.com/paulmillr/chokidar#performance).

**Comment by jackmcpickle** [comment]
Awesome thanks @jzvelc got mine running in docker with 

```
watch(path.resolve(./src/sass/**/*.*), {usePolling: true}, function() {
    gulp.start('compass');
  });
```

**Comment by salex772** [comment]
I have the same issue on OS X

    gulp.watch(path.join(tasks.images.src, '*.{' + tasks.images.extensions.join(',') + '}'), ['images']);

It sees only changes of files, file creating it does not see.

**Comment by shankiesan** [comment]
@jackmcpickle Your solution also worked for me in Docker, but makes CPU usage ridiculous for just a file watch (30% of a core on my old MBP). Have you got anywhere with using file system notifications rather than polling?

**Comment by jackmcpickle** [comment]
Hey, see my post on you https://github.com/floatdrop/gulp-watch/issues/228. 

also might be worth checkout the chokidar docs. https://www.npmjs.com/package/chokidar#performance

**Comment by jackmcpickle** [comment]
readdelay option might be worth checking out too. https://www.npmjs.com/package/gulp-watch#optionsreaddelay

**Comment by UltCombo** [comment]
Editing files in the host while watching them inside a VM through a shared folder is mostly broken, few VMs care to detect and emulate the file system events properly. Enabling the `usePolling` option usually fixes the issue, though. If you experience high CPU usage, try setting higher `interval` and `binaryInterval` options. As Jack mentioned, take a look at the [Chokidar docs](https://github.com/paulmillr/chokidar#performance) for details.
