### ISSUE TITLE
Error: pass strings or arrays of strings

### ISSUE THREAD

**Issue by simkessy** [floatdrop/gulp-watch#212]
I have this watch task that keeps failing after I updated the from v1 to the latest vid. 

    //Run task runner on any change or new file
    gulp.task('watch',function(){
        $.watch(['app/**/*'],function(files,cb){
            gulp.start('default', cb);
        })
    })

Error: 

```
PS C:\Users\Administrator\Dropbox\projects\spDash> gulp watch
[16:23:04] Using gulpfile ~\Dropbox\projects\spDash\gulpfile.js
[16:23:04] Starting 'watch'...
[16:23:04] Finished 'watch' after 84 ms
C:\Users\Administrator\Dropbox\projects\spDash\node_modules\gulp\node_modules\orchestrator\index.js:89
                                        throw new Error('pass strings or arrays of strings');
                                        ^

Error: pass strings or arrays of strings
    at Gulp.Orchestrator.start (C:\Users\Administrator\Dropbox\projects\spDash\node_modules\gulp\node_modules\orchestrator\index.js:89:12)
    at C:\Users\Administrator\Dropbox\projects\spDash\gulpfile.js:316:18
    at write (C:\Users\Administrator\Dropbox\projects\spDash\node_modules\gulp-watch\index.js:123:9)
    at C:\Users\Administrator\Dropbox\projects\spDash\node_modules\gulp-watch\node_modules\vinyl-file\index.js:52:4
    at C:\Users\Administrator\Dropbox\projects\spDash\node_modules\gulp-watch\node_modules\vinyl-file\node_modules\graceful-fs\graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by UltCombo** [comment]
In the latest version, the [callback](https://github.com/floatdrop/gulp-watch#callback-functionvinyl) no longer receives a callback argument.

That's because [gulp-batch](https://github.com/floatdrop/gulp-batch) has been decoupled from the core, but you can easily re-add it:

```
npm i -D gulp-batch
```

```js
// Run task runner on any change or new file
gulp.task('watch', function() {
    $.watch(['app/**/*'], $.batch(function(files, cb) {
        gulp.start('default', cb);
    }));
});
```

**Comment by jonschlinkert** [comment]
@UltCombo I'm guessing this can be closed based on lack of response

**Comment by UltCombo** [comment]
@jonschlinkert Sure, thanks. :smile:
The repository needs some housekeeping (documentation can be improved, tests need to be fixed, issues to triage and close), but I have very little time currently.

**Comment by EvanCarroll** [comment]
Getting the same error, I disagree with closing this and I'm unsure why I'm getting error still.

**Comment by UltCombo** [comment]
@EvanCarroll if you are actually experiencing the **same error** then I've explained it [above](https://github.com/floatdrop/gulp-watch/issues/212#issuecomment-165604593) and provided a solution.

Can you please read the [documentation](https://github.com/floatdrop/gulp-watch#usage) and [recipes](https://github.com/floatdrop/gulp-watch/blob/master/docs/readme.md)? I'm sure you will find all you need there. Otherwise, please report a proper issue with sample code, the expected and actual behavior.

**Comment by EvanCarroll** [comment]
Try this, if you could. Create an empty gulp file.. install gulp locally to your project. Run `gulp 2| less`

```
Error: pass strings or arrays of strings                                                                     
    at Gulp.Orchestrator.start (/home/ecarroll/code/rl/bulk-load/node_modules/orchestrator/index.js:89:12)   
    at /home/ecarroll/code/rl/bulk-load/node_modules/gulp/bin/gulp.js:129:20                                 
    at _combinedTickCallback (internal/process/next_tick.js:67:7)                                            
    at process._tickCallback (internal/process/next_tick.js:98:9)                                            
    at Function.Module.runMain (module.js:577:11)                                                            
    at startup (node.js:160:18)                                                                              
    at node.js:449:3                          
```

**Comment by UltCombo** [comment]
@EvanCarroll What is your gulpfile? Does it has the same code as this issue's [first comment](https://github.com/floatdrop/gulp-watch/issues/212#issue-122826508) or my [reply's](https://github.com/floatdrop/gulp-watch/issues/212#issuecomment-165604593) or something different?

**Comment by EvanCarroll** [comment]
No, just an empty gulpfile will do it.

**Comment by UltCombo** [comment]
Sorry, I don't understand how you can run the `gulp` command without defining a default gulp task in your `gulpfile`?

**Comment by EvanCarroll** [comment]
You don't understand how that generates the error, or you don't understand how you do it. Because it's *very* easy to do it. Just try it, it's not complex. Just to prove a point about something that generates this error. Just run this..

```bash
mkdir /tmp/asdf;
cd /tmp/asdf;
npm init -f;
npm install --save-dev gulp;
touch gulpfile.js;
$(npm bin)/gulp 2| less
```

**Comment by UltCombo** [comment]
I actually understand that you meant to create an empty gulpfile, but I thought it was a communication problem because as far as I see it, it makes no sense to try to run gulp with an empty gulpfile.

In any case, I just did as you said, and I just get:

```
[21:52:11] Using gulpfile C:\tests\empty-gulpfile\gulpfile.js
[21:52:11] Task 'default' is not in your gulpfile
[21:52:11] Please check the documentation for proper gulpfile formatting
```

As one would expect.

**Comment by UltCombo** [comment]
@EvanCarroll can you check if your gulpfile is actually empty? If it is, then it is supposed to throw an error like the one I've posted above.

**Comment by EvanCarroll** [comment]
And you ran it piping STDERR to less, right?

**Comment by UltCombo** [comment]
Ooops, I just did it piping to another process now. I can reproduce the error now, but it is actually different from the error reported here. :stuck_out_tongue:

As far as I can tell, the error is unrelated to `gulp-watch`. The issue seems is curious, though.

**Comment by EvanCarroll** [comment]
Excellent, well the error I produced is above. Fresh install in a new directory.

```text
node --version
v6.2.0
```

**Comment by UltCombo** [comment]
Yeah, I tested on Node 5.11.0 and can reproduce it as well. It seems to be an issue with the gulp core.

**Comment by EvanCarroll** [comment]
I'll go ahead and open a bug and reference this

**Comment by UltCombo** [comment]
Alright. :smile:
You can uninstall gulp-watch (`npm rm -D gulp-watch`) and the error is still reproducible, by the way.

**Comment by EvanCarroll** [comment]
https://github.com/gulpjs/gulp/issues/1679

**Comment by impsdc** [comment]
still
