### ISSUE TITLE
gulp-watch does not trigger while using a sync folder with vagrant

### ISSUE THREAD

**Issue by pYr0x** [floatdrop/gulp-watch#213]
i am using vagrant and a sync folder to map my folder on windows.
simple example:
```
var gulp = require('gulp'),
    watch = require('gulp-watch'),
    gutil = require('gulp-util');


gulp.task('watch', function(){
    watch('*.js', function () {
        gutil.log("file changed");
    });
});

gulp.task('default', ['watch']);
```
but gulp is not trigger **any** file changes

**Comment by UltCombo** [comment]
That's actually a problem with the Virtualbox shared folders implementation, which does not emit file system events to the VM.

Try the `usePolling: true` option:

```js
watch('*.js', { usePolling: true }, function () {
```

**Comment by pYr0x** [comment]
yeah, problem solved.
any restriction with usePolling?

**Comment by UltCombo** [comment]
Nope, but it may be more CPU-intensive. You can also set the `interval` option to define the file system polling interval in milliseconds if the default leads to too high CPU usage. See more info in the [Chokidar docs](https://github.com/paulmillr/chokidar#performance).
