### ISSUE TITLE
TypeError: vfs.watch is not function

### ISSUE THREAD

**Issue by roseanngabon** [floatdrop/gulp-watch#214]
I can't use gulp-watch as I encountering this issue
<code>TypeError: vfs.watch is not function</code>

This is my code:
<code>var watch = require('gulp-watch');</code>
<code>gulp.task('watch', function(){
	gulp.watch('js/**/*.js', ['scripts']);
});
</code>
>OS: Windows 8.1
>NPM version: 1.3.2

The error can be remove when using this code below but it won't work as for its desired function
<code>gulp.task('watch', function(){
	watch('js/**/*.js', ['scripts']);
});
</code>

**Comment by UltCombo** [comment]
I believe the callback must be a function, not an array of task names. Try:

```js
gulp.task('watch', function(){
  watch('js/*/.js', function() {
    gulp.start('scripts');
  });
}); 
```

Also, are you sure the `js/*/.js` glob is correct? Perhaps you meant `js/*.js` or `js/**/*.js`

**Comment by dreamypixy** [comment]
@UltCombo yes your correct, I need to change the glob to js/**/*.js. I missed that. Thank you. Any way, I've checked your snippet, and the error disappeared but the watch only hangs up in my terminal. I think it is related to when I've updated my gulp-watch globals.

**Comment by UltCombo** [comment]
Do you mean the watch is never triggered?
By the way, `js/*/.js` was your original glob, I suggested changing to `js/*.js` or `js/**/*.js`

**Comment by dreamypixy** [comment]
Sorry for wrong typo. :) I changed my glob to  js/**/*.js but the gulp watch just hangs up

**Comment by UltCombo** [comment]
Looks like you typo'd again then because it is still the same.

What do you mean "just hangs up"? It never fires the callback? Please double-check your glob pattern and your file structure.

Also, are you running this inside a Vagrant/Virtualbox setup?

**Comment by UltCombo** [comment]
Oh I see you are struggling with the markdown (`*` is used for italics and `**` for bold).  You can use backticks (\`) to delimit inline code snippets so those are not interpreted as formatting.

**Comment by UltCombo** [comment]
So I'm assuming you are using the `js/`**/*.js` glob. Do you have a `js` directory in the same level as your gulpfile?

If you can share a sample repository for testing that would be great. :smiley:

**Comment by dreamypixy** [comment]
You're right. It's the markdown that removes my (*). Thanks again
For additional info:
I'm not running it to any virtual machines.
Requested sample repo: https://github.com/dreamypixy/gulp-watch-test

About the "just hangs up": 
Watch statements  is not responding to source file changes. It only prints out like this in the terminal
<pre>
<code>
bash-4.3$ gulp watch
[02:18:00] Using gulpfile ~\Desktop\Code Demo\gulp-watch\gulpfile.js
[02:18:00] Starting 'watch'...
[02:18:00] Starting 'watch' after 6.26ms
</code>
</pre>

**Comment by UltCombo** [comment]
Thanks, I'll check it soon. By the way, do you have a `js` directory already created before you run gulp?

**Comment by UltCombo** [comment]
I tried your sample repository, it seems to be working for me. This is what I get when I edit the `scripts.js` file while the `gulp watch` command is running:

```
[10:52:47] Using gulpfile ~/gh-repos/gulp-watch-test/gulpfile.js
[10:52:47] Starting 'watch'...
[10:52:47] Finished 'watch' after 12 ms
[10:53:00] Starting 'scripts'...
[10:53:00] Finished 'scripts' after 9.82 ms
[10:53:02] Starting 'scripts'...
[10:53:02] Finished 'scripts' after 2.72 ms
[10:53:05] Starting 'scripts'...
[10:53:05] Finished 'scripts' after 1.51 ms
```

By the way, did you try updating your dependencies? Try `rm -rf node_modules && npm install`

**Comment by UltCombo** [comment]
Closing as inactive.
