### ISSUE TITLE
TypeError: listener must be a function

### ISSUE THREAD

**Issue by csonlai** [floatdrop/gulp-watch#215]
watch(paths.src.html, {verbose: true}, function(){
            copyHtml();
        });

**throw error:**
TypeError: listener must be a function
    at DestroyableTransform.addListener (events.js:197:11)

**Comment by UltCombo** [comment]
Are you sure the error comes from gulp-watch? Your usage seems correct.

**Comment by csonlai** [comment]
yes, when i modify the file, it throw this error..

**Comment by csonlai** [comment]
oh i know , not the bug in gulp-watch 
thank you ultCombo~
