### ISSUE TITLE
Watch won't trigger if some directory in the path starts with "!"

### ISSUE THREAD

**Issue by dcby** [floatdrop/gulp-watch#216]
I found that callback never fired if path that being watched contains a directory whose name is started with "!" (tested on Windows only).

Assume we have three files:
1. c:\test\1.txt
2. c:\\_!test\1.txt
3. c:\\!test\1.txt

```javascript
var gulp = require("gulp"), // 3.9.0
	watch = require("gulp-watch"); // 4.3.5

var path = <path to file>;

gulp.task("watch", function () {
	watch(path, function () {
		console.log("trigger");
	});
});
```

The callback WILL trigger in cases 1 and 2.
The callback WON'T trigger in case 3.

Although `gulp.watch` works correctly in all cases.

**Comment by UltCombo** [comment]
gulp-watch uses chokidar which uses anymatch which uses micromatch. Micromatch treats globs beginning with `!` as negation globs (see "Negation patterns" in the [docs](https://github.com/jonschlinkert/micromatch#usage)).

@jonschlinkert Is there a way to escape the `!` or an option to disable negation globs in micromatch?

**Comment by dcby** [comment]
What `gulp.watch` uses? Is it not chokidar?

**Comment by UltCombo** [comment]
gulp 4 uses chokidar. IIRC gulp 3 uses gaze.

**Comment by UltCombo** [comment]
If I'm interpreting [this code](https://github.com/paulmillr/chokidar/blob/9d237a9d7b4e669586cfd6301cebb17f717c9ea0/index.js#L358-L361) correctly, Chokidar uses [glob-parent](https://github.com/es128/glob-parent#usage) + anymatch, so the path that gets passed to micromatch begins with `!` and is treated as a negation glob.

**Comment by dcby** [comment]
As per code revision the simplest solution would be to add an option to ignore negation for micromatch. To make escaping work several repos must be tuned together.

**Comment by UltCombo** [comment]
I'm not sure. Adding an option to ignore negation also means that all packages in-between would forward that option. I believe that is not true with chokidar nor anymatch.

**Comment by dcby** [comment]
Damn, true. No chokidar nor anymatch forwards options.

**Comment by UltCombo** [comment]
How about using braces as a form of escaping?

```js
watch('C:\\{!}test\\1.txt', function(files) {
  console.log('fired');
});
```

This seems to work for me.

**Comment by dcby** [comment]
Nice one!

But because it won't work if you use it as base:
```javascript
watch('1.txt', { base: 'C:\\{!}test' }, function(files) {
  console.log('fired');
});
```
you have to do:
```javascript
var p = path.join("C:\\!test".replace(/!/g, "{!}"), "1.txt");
watch(p, function(files) {
  console.log('fired');
});
```

Thanks!

**Comment by UltCombo** [comment]
Nice, no problem. :smile:

By the way, if you'd like you can open an issue in the [glob-parent repository](https://github.com/es128/glob-parent) as well. I believe `!` shouldn't have special meaning unless they are the first character in a glob pattern or `!()` extglob.

**Comment by jonschlinkert** [comment]
I just saw the convo, looks like everything is good? If not let me know if you still have questions.

> Is there a way to escape the ! or an option to disable negation globs in micromatch?

try [options.nonegate](https://github.com/jonschlinkert/micromatch/blob/master/index.js#L81). 

> believe ! shouldn't have special meaning unless they are the first character in a glob pattern or !() extglob.

that's correct. although if the path is transformed before it's passed to micromatch that could effect the positioning of `!`.

**Comment by UltCombo** [comment]
> that's correct. although if the path is transformed before it's passed to micromatch that could effect the positioning of `!`.

Exactly. I believe the issue is that [glob-parent](https://github.com/es128/glob-parent) is incorrectly transforming the path: `globParent('foo/!bar/1.txt')` returns `foo`, should be `foo/!bar`.

**Comment by jonschlinkert** [comment]
hmm, if so I would think the cause is either `path.dirname` or `is-glob` - the latter being far more likely. I'll go look

**Comment by UltCombo** [comment]
True, both `is-glob` and `glob-parent` packages give special meaning to the `!` in `'foo/!bar/1.txt'`, when I believe they shouldn't.

**Comment by dcby** [comment]
Actually, why not? Perhaps you want to match
```
foo/any/1.txt
foo/whatever/1.txt
```

But ignore
`foo/bar/1.txt`

**Comment by jonschlinkert** [comment]
It's is-glob. `glob-parent` just tries to get the dirname. 

I fixed it locally. but I'd like your feedback, and @es128 before merging. it's a minor fix, I tested it in is-glob and glob-parent, and gulp-watch. everything is passing. however... although this is technically a "patch", it seems just as likely - or more likely - that a patch bump will break more people's code than the other way around.

thoughts?

**Comment by jonschlinkert** [comment]
> perhaps you want to match

extglobs to the rescue! see [these crazy tests](https://github.com/jonschlinkert/micromatch/blob/master/test/bash-extglob.js#L27)

**Comment by UltCombo** [comment]
> Actually, why not?

Because that's not how micromatch and other globbing libraries work. :wink:
You can see Jon's linked examples to achieve that in a more standard way.

> although this is technically a "patch", it seems just as likely - or more likely - that a patch bump will break more people's code than the other way around.

Yep, this is indeed a bug fix which technically should be a patch release, but there are likely people relying on this bug, which makes it a breaking change. Hard decisions. :disappointed:

**Comment by dcby** [comment]
extglob makes sence.

Agreed about breaking changes.

**Comment by es128** [comment]
@jonschlinkert what's the change? Eliminate `!` from glob-relevant characters, or just ensure it's the first character in order to match? 

I don't think anyone is relying on negation based on a mid-string `!` since it wouldn't actually work regardless (unless using extglob - in which case the parens will trip off is-glob anyway), so it seems to me this is ok as a patch change.

glob-parent does not account for actual glob negation at all currently, but I haven't heard anyone complain about that yet. So it would appear all its consuming libs already handle negated globs separately in some way - either not having any need to derive the non-magic parent dir since it just acts as a filter, or knowing to strip off the `!` before running the string through glob-parent.

**Comment by jonschlinkert** [comment]
> what's the change?

ensure that the `!` is either the first character, or is directly preceding a `(` for an extglob

> I don't think anyone is relying on negation based on a mid-string

yeah that's a good way to put it. I agree. I think this should be a patch too. I'll make the change and comment here when it's done

**Comment by es128** [comment]
> or is directly preceding a ( for an extglob

seems unnecessary - won't the presence of the `(` just match on its own?

**Comment by jonschlinkert** [comment]
the main issue is that `foo/!bar` is considered a valid, non-glob filepath, but `foo/!(bar)` is an extglob. `is-glob` would be wrong on the first one. If you want to think it over I'll just keep testing before we do anything.

**Comment by es128** [comment]
What I'm trying to say is that it seems redundant to look for `!(` in is-glob because it will already return `true` just from the `(` being there.

**Comment by jonschlinkert** [comment]
oh I see what you mean. point being that we only need to change the regex to match on the leading `!`, since `(` is already taken care of... good catch
