### ISSUE TITLE
Gulp-watch detects changes when file is just opened.

### ISSUE THREAD

**Issue by gintsgints** [floatdrop/gulp-watch#219]
Whenever I open file in Code editor or Atom, gulp-watch fires changes continuously. Editors like Sublime text fires changes only once per show/hide editor window.
Webstorm tough works fine.

**Comment by UltCombo** [comment]
Can you try disabling all of your editor's plugins/extensions and try again? Looks like you have some extension that auto-saves the file.

**Comment by gintsgints** [comment]
What changes on files are under detection? How I can check that myself? May be file modification date/time?

**Comment by gintsgints** [comment]
Yes there is changed files but with *.js extension. But I have next match search:

```
    gulp.watch(appDev + '**/*.ts', ['build-ts']);
    gulp.watch(assetsDev + 'scss/**/*.scss', ['build-css']);
    gulp.watch(assetsDev + 'img/*', ['build-img']);
```

**Comment by UltCombo** [comment]
File changes are tracked by [Chokidar](https://github.com/paulmillr/chokidar). It emits a change event when the file's modification time is changed, yes.

**Comment by gintsgints** [comment]
Ok. I go for Chokidar component. Because I can repeat that behaviour with it only.

Ty. For support.

**Comment by gintsgints** [comment]
And date time modified has not changed :)

**Comment by gintsgints** [comment]
Is it possible to set chokidar option - "usePolling: true"

With this option it works fine

**Comment by UltCombo** [comment]
Yes, gulp-watch passes the options object directly to Chokidar.

**Comment by UltCombo** [comment]
See: https://github.com/floatdrop/gulp-watch#options
