### ISSUE TITLE
Doesn't find new symlinks

### ISSUE THREAD

**Issue by whomba** [floatdrop/gulp-watch#220]
If I have /my/folder/with/symlinks which has N symlinks to files, then add new symlinks to files, gulp-watch doesn't see / pick them up.

Thoughts?

**Comment by UltCombo** [comment]
I guess this should work. It is probably a bug in [Chokidar](https://github.com/paulmillr/chokidar).

Let me see if I understood: you are watching a folder like `/my/folder/with/symlinks` or `/my/folder/with/symlinks/*` and then create a new symlink inside of it. Is that the use case? By the way, what OS are you using?

**Comment by whomba** [comment]
Yes, basically, I have ```/my/folder/with/symlinks``` which might have 5
symlinks to 5 files in other folders, I have the following
```
gulp.task('watchSymlinks', function(){
  watch('/my/folder/with/symlinks/**/*.scss', function(){
    //do something
  });
});
```
and when I add a file somewhere else, it creates a new symlink to that file
in ```/my/folder/with/symlinks``` however that new symlink to the new file
is never picked up.

**Comment by whomba** [comment]
Yes, basically, I have `/my/folder/with/symlinks`  which might have 5
symlinks to 5 files in other folders, I have the following
```
gulp.task('watchSymlinks', function(){
  watch('/my/folder/with/symlinks/**/*.scss', function(){
    //do something
  });
});
```
and when I add a file somewhere else, it creates a new symlink to that file
in ```/my/folder/with/symlinks``` however that new symlink to the new file
is never picked up.


OS: Red Hat Enterprise & Mac OSX

**Comment by UltCombo** [comment]
Oh, I see.
Can you try the `{ usePolling: true }` option? It works around a bunch of bugs, might be worth a try.
In any case, it would be nice to have this reported in the [Chokidar repository](https://github.com/paulmillr/chokidar), which is responsible for gulp-watch's file system watching capabilities.

**Comment by UltCombo** [comment]
By the way, are any of the OS's you have tested inside of a virtual machine?

**Comment by whomba** [comment]
I will try the ```usePolling``` in a little bit.

Yes - RHE is a virt, Mac is not.

**Comment by UltCombo** [comment]
Oh that is probably it. File watching inside VMs is pretty buggy on virtually all VMs/file system watchers. The `usePolling` option usually helps with that.

**Comment by UltCombo** [comment]
Closing as inactive. Please comment/reopen if you are still experiencing this issue.
