### ISSUE TITLE
Should release v4.3.6

### ISSUE THREAD

**Issue by mrtbld** [floatdrop/gulp-watch#221]
If you have the time, it would be great to publish a new release on npm to include the latest fixes.

Here are the changes since last release v4.3.5:
https://github.com/floatdrop/gulp-watch/compare/v4.3.5...master.

Cheers

**Comment by UltCombo** [comment]
I don't have publishing permissions, so we need @floatdrop to publish a new version and/or add me as a maintainer in the npm package.

**Comment by floatdrop** [comment]
@UltCombo that's weird, fixed.
