### ISSUE TITLE
4.3.5 do not see new files

### ISSUE THREAD

**Issue by salex772** [floatdrop/gulp-watch#223]
Gulp-watch 4.3.5 can only detect changes on files that were already created before watch task was started. New files are ignored. I use OS X. 

watch task item:

    gulp.watch(path.join(tasks.images.src, '*.{' + tasks.images.extensions.join(',') + '}'), ['images']);

**Comment by UltCombo** [comment]
By the way, are you running gulp inside a VM?

In any case, try setting the `useFsEvents: false` option to see if it changes anything.

**Comment by evenfrost** [comment]
@salex772 Seems you are using native `gulp.watch` API, not the `gulp-watch` package.

**Comment by UltCombo** [comment]
Good catch, @evenfrost.
I should've paid more attention to the sample code.
