### ISSUE TITLE
Does it need gulp.src ?

### ISSUE THREAD

**Issue by liximomo** [floatdrop/gulp-watch#224]
```javascript
 gulp.src('css/**/*.css')
        .pipe(watch('css/**/*.css'))
```

what gulp.src does for watch('css/**/*.css')?

**Comment by UltCombo** [comment]
`gulp-watch` returns a pass-through stream, so the vinyl objects emitted by `gulp.src` will pass directly to the next streams in the pipeline. The `watch` stream will then emit files as they are changed. For example:

```js
gulp.task('minifyCSS', function() {
  gulp.src('css/**/*.css') // Pass all css files to cssmin upon starting this task
    .pipe(watch('css/**/*.css')) // Watch css files and pass them to cssmin when they are changed
    .pipe(cssmin())
    .pipe(gulp.dest('dist/css'));
});
```

I believe you can drop `gulp.src` if you disable the [`ignoreInitial` option](https://github.com/floatdrop/gulp-watch#optionsignoreinitial). That is, the example above should be equivalent to:

```js
gulp.task('minifyCSS', function() {
  watch('css/**/*.css', { ignoreInitial: false })
    .pipe(cssmin())
    .pipe(gulp.dest('dist/css'));
});
```
