### ISSUE TITLE
Not emitting end event

### ISSUE THREAD

**Issue by mathemagik** [floatdrop/gulp-watch#225]
Hello,

It's possible that I'm doing something wrong, but I've spent a number of hours modeling my Gulp build after the example to be found in the readme.md. Here's the code:

![screen shot 2016-05-05 at 5 39 43 pm](https://cloud.githubusercontent.com/assets/16509501/15058107/717942e0-12e8-11e6-91f7-51ba5450d995.png)

For whatever reason, when I use it, no end event is ever emitted. I'm running Node version 6.0.0. Is anyone else having issues with this? The end event emits only when I call .close, which is obviously no good for asynchronous work.

**Comment by UltCombo** [comment]
`gulp-watch`'s stream mode returns an endless stream by design; this is noted in the repository's description. The reasoning is that while the watcher is running, files may be changed and gulp-watch will emit them as the changes are detected.

As for the solution, in most cases you should either the callback version (if you need an `end`) or the endless stream version in case you don't.

I see that you are already using the callback version so you may not need the endless watch stream inside of it. However, your sample code has been overly simplified so I cannot determine why you you would want to use the endless watch stream inside the watch callback. I believe in most cases you would just remove the watch stream from there, but let me know if you need help with your real use case.

**Comment by UltCombo** [comment]
And yeah, I believe the documentation can be improved in this regard. It should reinforce that the stream is endless by design and the callback version should be used if your stream pipeline needs an `end` event.

**Comment by mathemagik** [comment]
@UltCombo, that was very well explained. Thanks so much for the help. 

As for what I was trying to do, I have to use Gulp to upload to Shopify--a platform which handles hosting for you. In other words, while I can work on the files locally, I must rely on their servers to render everything. Uploading only modified files using gulp-watch works out incredibly well: 

<img width="875" alt="screen shot 2016-05-06 at 10 29 50 am" src="https://cloud.githubusercontent.com/assets/16509501/15076070/bf3997cc-1375-11e6-9b84-584bb16d0b01.png">


However, I wanted to take it one step further and implement browser-sync. Here's an example of how I was doing that.

<img width="854" alt="screen shot 2016-05-06 at 10 38 01 am" src="https://cloud.githubusercontent.com/assets/16509501/15076253/c63866d8-1376-11e6-8467-08b339c05c65.png">


Of course, the obvious issue is that it reloads before the files have finished uploading, and I wanted to try to avoid using a janky solution like setTimeout. Instead, I decided I wanted to use the callback structure suggested in the docs for gulp-watch. However, I couldn't even get a trivial example to work.

<img width="916" alt="screen shot 2016-05-06 at 10 41 46 am" src="https://cloud.githubusercontent.com/assets/16509501/15076357/3766ce6c-1377-11e6-8e77-c76e36f1ab94.png">

As you can see, my example is identical to the docs. The only difference is that I changed the glob. Either way, for some reason the end event isn't emitted, unless I manually call .close(). Perhaps I'm missing something obvious? I'm willing to use setTimeout. I just don't like the thought of missing something conceptual, especially if it should be apparent. :-)

**Comment by UltCombo** [comment]
One of the problems is that you're creating a watch stream inside of a watch callback. That is, a new watch stream that never ends is created each time the watch callback fires. You should use either the  callback version (`watch('...', function() {/*...*/})` or the `watch('...').pipe(function() {/*...*/})` version.

To upload individual files you could do something like:

```js
var streamify = require('stream-array'); // npm install stream-array

plugins.watch('...', function (event) {
    streamify([event]).pipe(plugins.shopifyUpload({/*...*/})).on('end', function() {
        setTimeout(function() {
            plugins.browserSync.reload();
        }, 5000);
    });
});
```

And as you have mentioned, the shopify-upload plugin [re-emits files before finishing uploading them](https://github.com/mikenorthorp/gulp-shopify-upload/blob/ce97925a82277a05024f8da0e96cd43d4272154d/index.js#L218-L222). Perhaps you can edit/fork the plugin and change that to call `stream.push` and `cb` after the upload is complete so you wouldn't need the `setTimeout` hack.

**Comment by mathemagik** [comment]
Hey, @UltCombo. I figured I was doing something naughty inside of a callback, but I wasn't getting the results I wanted on my own, so I thought it best to not deviate from the docs, even if adhering to them meant doing something that seemed a little unintuitive.

Either way, I very strongly appreciate your willingness to help. I might eventually fork shopify-upload, but for now, I'll probably just use setTimeout. :-) It's hacky, but it works 95% of the time. I suppose I'll just command + R the other 5%.

**Comment by UltCombo** [comment]
Glad to be of help. :smiley:
