### ISSUE TITLE
Glob problem

### ISSUE THREAD

**Issue by guohuihot** [floatdrop/gulp-watch#226]
```
glob --> /images/**/*.{png,gif,jpg,jpeg}
```
When `ggg.png` increases, the normal should be `ggg.png(add)`, but this is the result of the following
```
images\line-dot.png(change)
images\line1.png(change)
images\loginbg.jpg(change)
images\l\ggg.png(add)
```
Lists all files that start with `l` in the images directory

**Comment by UltCombo** [comment]
Can you post a gulpfile with a minimum test case?

**Comment by guohuihot** [comment]
tree
```
├── gulpfile.js
├── images
│   ├── a
│   │   ├── ddd.png
│   │   └── Thumbs.db
│   ├── a2.png
│   ├── abc.png
│   ├── adef.png
│   └── amap.png

```
gulpfile.js
```
var gulp = require('gulp'),
    watch = require('gulp-watch');

gulp.task('test', function() {
    watch('./images/**/*.{png,gif,jpg,jpeg}', function(file) {
        console.log(file.path, file.event);
    })
})
```

**Comment by UltCombo** [comment]
It looks like you are on Windows, right? Are you running gulp from `cmd.exe` or Cygwin or Bash (through the Ubuntu subsystem)?

Do you have the latest version of the gulp-watch package installed? Are using any particular image editor?

I cannot reproduce the issue on my machine, I just get a `ddd.png change` on the terminal when running your gulpfile through `cmd.exe` and editing the `ddd.png` with Paint.

One random shot, try enabling the [`usePolling`](https://github.com/paulmillr/chokidar#performance) option to see if it helps:

```js
    watch('./images/**/*.{png,gif,jpg,jpeg}', { usePolling: true }, function(file) {
        console.log(file.path, file.event);
    })
```

**Comment by guohuihot** [comment]
Images the following folder name is "a", the file name if "a" at the beginning

**Comment by guohuihot** [comment]
Oh Yeah, Plus this setting is good,
```
{ usePolling: true }
```
