### ISSUE TITLE
gulp-watch does not install properly

### ISSUE THREAD

**Issue by elhampour** [floatdrop/gulp-watch#230]
i want to install gulp-watch package but i get this error :

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12`

how should i fix this error ?

**Comment by UltCombo** [comment]
That's not an error, it is just a warning telling you that an **optional** dependency was not installed as it is not compatible with your platform. See [Chokidar - Troubleshooting](https://github.com/paulmillr/chokidar#install-troubleshooting):

> - `npm WARN optional dep failed, continuing fsevents@n.n.n`
>   - This message is normal part of how `npm` handles optional dependencies and is not indicative of a problem. Even if accompanied by other related error messages, Chokidar should function properly.

The `fsevents` package wraps low-level OS X file system APIs, it is just an optional dependency that provides improved performance in OS X systems. That said, the warning message is a normal and expected part of the installation process in Windows and Linux operating systems, it is not indicative of an error. You can ignore the warning and rest assured that the package will work just fine. :smiley:
