### ISSUE TITLE
what is the differences between this plugin and gulp.watch()?

### ISSUE THREAD

**Issue by bi-kai** [floatdrop/gulp-watch#245]
what is the differences between this plugin and gulp.watch()?

**Comment by UltCombo** [comment]
gulp's built-in `gulp.watch` only notifies you that changes have occurred, but it doesn't tell you what file(s) have changed.

Now, both modes of gulp-watch (streaming/callback) will emit a Vinyl file (gulp's virtual file format) that you can work with. This often makes implementing incremental builds easier and more efficient than `gulp.src()`ing all files and piping them through gulp-changed/gulp-newer, for example.

Another difference is the underlying file system watcher library: gulp v3 uses [Gaze](https://github.com/shama/gaze), while gulp-watch uses [Chokidar](https://github.com/paulmillr/chokidar). We have used Gaze in the past as well, and switching to Chokidar proved to solve several issues. Note that gulp v4 is also moving to Chokidar.

By the way, I believe we can make this distinction more clear in the documentation. Patches are welcome.

**Comment by bi-kai** [comment]
It's clear, thanks.
