### ISSUE TITLE
Watched unexpected filepath

### ISSUE THREAD

**Issue by hooriza** [floatdrop/gulp-watch#250]
gulp-watch version: `4.3.9`
Globs: `["**/*","!**/@sprites.png"]`
Filepath: `/Users/myname/Developes/work/app/src/img/@2x/@sprites.png`
Event: `change`
Process CWD: `/Users/myname/Developes/work/app`
Options:

``` js
{
  "events": [
    "add",
    "change",
    "unlink"
  ],
  "ignoreInitial": true,
  "readDelay": 10,
  "cwd": "src/img/@2x"
}
```

**Comment by jonschlinkert** [comment]
hmm, I'll look at micromatch and make sure we have sufficient coverage for `@`. I don't think that's it but it's worth a look anyway...

what os / file system are you using?

**Comment by floatdrop** [comment]
Dup https://github.com/floatdrop/gulp-watch/issues/251
