### ISSUE TITLE
Problem with watch.

### ISSUE THREAD

**Issue by ronaldohoch** [floatdrop/gulp-watch#252]
Hello!

I have a fork in a folder running a gulp watch of these project, so I changed the gulp.dist to a vendor folder in my project away from the original fork folder (See link to image bellow).

In my main project folder I've another gulp.watch watching the vendor folder for changes, but... When the fork gulp.watch throw the files to my vendor folder, the gulp watch don't run the task.

I don't know if it is a bug, I think it's because I don't run clean task and the file is there, if I go to the file and manually save, the vendor's watch task, run.

The image link: http://prntscr.com/ccxryu

**Comment by jonschlinkert** [comment]
@ronaldohoch can you past the minimum necessary code from `gulpfile.js` so we can reproduce the issue?

**Comment by ronaldohoch** [comment]
Fork gulpfile -> http://pastebin.com/w5LkWpPg
Main gulpfile -> http://pastebin.com/fTH73dps

CLI version 3.9.1

However... I've made a litle project with 2 simple files that worked for me :(

**Comment by ronaldohoch** [comment]
Sorry for the issue, i've solved the problem..
