### ISSUE TITLE
`nopt` module is missing and throwing exception

### ISSUE THREAD

**Issue by shobhitsharma** [floatdrop/gulp-watch#255]
Seems to be removed or moved, please check.

``` bash
Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by UltCombo** [comment]
The unit tests from two days ago are passing, and npm no longer allows unpublishing packages older than 24 hours, so this seems unlikely.

Perhaps you have ended up with a broken npm install? Please try doing a clean install (`rm -rf node_modules && npm install`) to check if it helps. Several releases in npm 3.x had bugs regarding partial install/update that would make some packages go missing. You may want to update your npm too (`npm install -g npm`).
