### ISSUE TITLE
How i can console.log() then task ended?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [floatdrop/gulp-watch#258]
``` coffeescript
gulp.task 'modules', =>
    watch MODULES.SRC, ignoreInitial: off
    .on 'ready', => console.log 'ready!'
    .on 'change', => console.log 'change!'
    .pipe do sourcemaps.init
    .pipe do coffee
    .pipe sourcemaps.write '.'
    .pipe gulp.dest MODULES.DEST
```

In first run compile all files and console.log('build complete') ONCE!
Then if change one file, compile only this file and console.log('build complete') ONCE!
I can use "ready" and "change" events, but i need use it events on END pipes chine, after gulp.dest.

How can I do it?

**Comment by UltCombo** [comment]
The stream returned from `watch()` is an infinite stream, it will never emit an `end` event (unless you close the watcher).

If you need the `end` event for your gulp task, you can use gulp-watch's callback mode:

```cs
gulp.task 'modules', =>
    watch MODULES.SRC, ignoreInitial: off, =>
        gulp.src MODULES.SRC
        .pipe do sourcemaps.init
        .pipe do coffee
        .pipe sourcemaps.write '.'
        .pipe gulp.dest MODULES.DEST
```

**Comment by UltCombo** [comment]
Closing, please reopen if you need further help.
