### ISSUE TITLE
Why flush is not called when pipe to another plugin

### ISSUE THREAD

**Issue by fwang2002** [floatdrop/gulp-watch#260]
with gulp.src, the transform and flush are called, but watch only calls transform.

**Comment by UltCombo** [comment]
`gulp.src` emits a finite amount of objects: it scans the file system once and emits the files currently on disk that match the glob pattern(s), then emits the `end`/`flush` event.
The stream returned from `gulp-watch` is intentionally an infinite stream: it will emit files as they are added/modified/removed, the stream stays open for as long as the file watcher is running.

If you need the end/flush event in your pipeline, please use the callback API. See the [Usage section](https://github.com/floatdrop/gulp-watch#usage) for an example; see also #258.
