### ISSUE TITLE
Watch acting on events

### ISSUE THREAD

**Issue by jerome724** [floatdrop/gulp-watch#266]
node version: 7.0.0
gulp version: 3.9.1
gulp-watch version: 4.3.11

Gulpfile:

```js
const
	gulp = require('gulp'),
	plugins = require('gulp-load-plugins')();

gulp.task('coffee:lint', () => {
	gulp.src('./_coffeescript/**/*.coffee')
    .pipe(plugins.watch('./_coffeescript/**/*.coffee'))
		.pipe(plugins.coffeelint())
		.pipe(plugins.coffeelint.reporter('coffeelint-stylish'))
});

gulp.task('coffee:build', () => {
	gulp.src('./_coffeescript/**/*.coffee')
    .pipe(plugins.watch('./_coffeescript/**/*.coffee'), {
      name: 'coffee:build',
      read: false
    })
		.pipe(plugins.sourcemaps.init())
		.pipe(plugins.coffee())
		.pipe(plugins.sourcemaps.write())
		.pipe(gulp.dest('./_javascript'));
});

gulp.task('default', ['coffee:lint', 'coffee:build']);
```

When i now change a file in ``./_coffeescript/**/*.coffee`` nothing happens.

**Comment by UltCombo** [comment]
I believe `sourcemaps.write()` waits for the stream to end, which never happens in gulp-watch's endless stream mode. You will need to use the callback mode, e.g. to compile individual files:

```js
var streamify = require('stream-array');
plugins.watch('./_coffeescript/**/*.coffee', {
    name: 'coffee:build',
    read: false
}, function(file) {
    streamify(file)
      .pipe(plugins.sourcemaps.init())
      .pipe(plugins.coffee())
      .pipe(plugins.sourcemaps.write())
      .pipe(gulp.dest('./_javascript'));
});
```

OR

```js
plugins.watch('./_coffeescript/**/*.coffee', {
    name: 'coffee:build',
    read: false
}, function() {
    gulp.src('./_coffeescript/**/*.coffee')
      .pipe(plugins.changed()) // Use gulp-changed or gulp-newer to compile changed files only
      .pipe(plugins.sourcemaps.init())
      .pipe(plugins.coffee())
      .pipe(plugins.sourcemaps.write())
      .pipe(gulp.dest('./_javascript'));
});
```

We may need some more doc clarifications and examples about 1:1/1:n file mappings and incremental builds. Especially, the recipes section could do with some additions.

I'm considering to make some changes in gulp-watch v5 to streamify the callback's changed file automatically, so users don't have to wrap it in a stream manually. It is a breaking change, so it needs more consideration before implementing such option and making it a default or not. The [gulp-batch](https://www.npmjs.com/package/gulp-batch) plugin comes to mind, also. I'll open an issue or PR for discussion after giving this more thought.

**Comment by jerome724** [comment]
Hey!

Thanks for the help, unfortunately it is still not working, i even tried to remove the sourcemaps, but that didn't worked either. 

```js
gulp.task('coffee:build', () => {
  plugins.watch('./_coffeescript/**/*.coffee', {
    name: 'coffee:build',
    read: false
  }, () => {
    gulp.src('./_coffeescript/**/*.coffee')
      .pipe(plugins.changed('./_javascript', {hasChanged: plugins.changed.compareSha1Digest}))
      .pipe(plugins.coffee())
      .pipe(gulp.dest('./_javascript'));
  });
});
```

**Comment by UltCombo** [comment]
It seems your setup is fine, I can't spot anything wrong at first sight.
When you edit `.coffee` files inside the `_coffeescript` directory, it doesn't do anything?

**Comment by jerome724** [comment]
Correct, gulp does every task, ``coffee:lint`` and ``coffee:build``, but at the end nothing got changed.

```
[18:59:41] Starting 'coffee:lint'...
[18:59:41] Finished 'coffee:lint' after 111 ms
[18:59:41] Starting 'coffee:build'...
[18:59:41] Finished 'coffee:build' after 78 ms
[18:59:41] Starting 'default'...
[18:59:41] Finished 'default' after 39 μs
```

I renamed ``_coffeescript`` to ``coffeescript`` and back to ``_coffeescript`` and suddenly it works, but only without gulp-watch. 

This is working fine
```js
gulp.task('coffee:build', () => {
    gulp.src('./_coffeescript/**/*.coffee')
      .pipe(plugins.changed('./_javascript'))
      .pipe(plugins.coffee())
      .pipe(gulp.dest('./_javascript'));
});
```

and this is not working, not even compiles the coffee to js
```js
gulp.task('coffee:build', () => {
  plugins.watch('./_coffeescript/**/*.coffee', {
    name: 'coffee:build',
    read: false
  }, () => {
    gulp.src('./_coffeescript/**/*.coffee')
      .pipe(plugins.changed('./_javascript'))
      .pipe(plugins.coffee())
      .pipe(gulp.dest('./_javascript'));
  });
});
```

this is really really weird.

**Comment by jerome724** [comment]
closed, again thanks for your help @UltCombo!

**Comment by UltCombo** [comment]
Heheh, no problem! 😄
