### ISSUE TITLE
Watched unexpected filepath

### ISSUE THREAD

**Issue by scofalik** [floatdrop/gulp-watch#267]
Node.js version: `v6.9.1 win32 x64`
gulp-watch version: `4.3.11`
Globs: `"c:\\cks\\ckeditor5-engine\\@(src|tests)\\**\\*"`
Filepath: `C:\cks\ckeditor5-engine\tests\model\delta\transform\testfield.js`
Event: `change`
Process CWD: `C:\cks\ckeditor5`
Options:
```js
{
  "events": [
    "add",
    "change",
    "unlink"
  ],
  "ignoreInitial": true,
  "readDelay": 10,
  "base": "c:\\cks",
  "nodir": true,
  "read": true,
  "buffer": true,
  "cwd": "C:\\cks\\ckeditor5",
  "dot": false,
  "silent": true,
  "nonull": false,
  "cwdbase": false
}
```

**Comment by jonschlinkert** [comment]
I'm guessing it's because of the backslashes. Only forward slashes can be used as path separators in glob patterns, regardless of platform.

**Comment by UltCombo** [comment]
@jonschlinkert Is that the case? I thought Chokidar supported backslashes as well. And gulp-watch now converts backslashes to forward slashes when it is safe IIRC.
