### ISSUE TITLE
Watched unexpected filepath

### ISSUE THREAD

**Issue by cayetanobv** [floatdrop/gulp-watch#272]
Node.js version: `v6.9.2 linux x64`
gulp-watch version: `4.3.11`
Globs: `"./**/*.js"`
Filepath: `/usr/src/app/node_modules/.bin/mocha`
Event: `add`
Process CWD: `/usr/src/app`
Options:
```js
{
  "events": [
    "add",
    "change",
    "unlink"
  ],
  "ignoreInitial": true,
  "readDelay": 10
}
```

**Comment by jonschlinkert** [comment]
remove `./` from the glob, see if that works

**Comment by cayetanobv** [comment]
Thanks. Now it is working without errors.

**Comment by UltCombo** [comment]
Thanks! That's useful debugging information. I will try to make an unit test tonight and hopefully fix that for the next release.

Of course, if anyone is up to it feel free to take a look and tackle this as well. It should be fairly straightforward.

**Comment by UltCombo** [comment]
I tried to add a test for this issue here: https://github.com/floatdrop/gulp-watch/pull/273/files

However, Travis is still passing for all Node versions. Any ideas? Maybe I'm missing something?
