### ISSUE TITLE
Watched unexpected filepath

### ISSUE THREAD

**Issue by abdihaikal** [floatdrop/gulp-watch#274]
Node.js version: `v7.4.0 win32 ia32`
gulp-watch version: `4.3.11`
Globs: `["./app/package.json"]`
Filepath: `D:\project\app\package.json`
Event: `add`
Process CWD: `D:\project\app`
Options:
```js
{
  "events": [
    "add",
    "change",
    "unlink"
  ],
  "ignoreInitial": true,
  "readDelay": 10
}
```

**Comment by UltCombo** [comment]
Does your code change the working directory at some point (like calling `process.chdir` inside the gulpfile)?
