### ISSUE TITLE
Watched unexpected filepath

### ISSUE THREAD

**Issue by haizhilin2013** [floatdrop/gulp-watch#276]
Node.js version: `v6.0.0 win32 x64`
gulp-watch version: `4.3.11`
Globs: `["E:\\wangjian\\workspace\\reconsitution\\Front_End\\build/app_pc/index/index.html","E:\\wangjian\\workspace\\reconsitution\\Front_End\\build/app_pc/user/index.html","E:\\wangjian\\workspace\\reconsitution\\Front_End\\src/app_pc/.htaccess","E:\\wangjian\\workspace\\reconsitution\\Front_End\\src/app_pc/favicon.ico"]`
Filepath: `E:\wangjian\workspace\reconsitution\Front_End\build\app_pc\index.html`
Event: `add`
Process CWD: `E:\wangjian\workspace\reconsitution\Front_End`
Options:
```js
{
  "events": [
    "add",
    "change",
    "unlink"
  ],
  "ignoreInitial": true,
  "readDelay": 10
}
```

**Comment by haizhilin2013** [comment]
OK

**Comment by UltCombo** [comment]
This is a bug in the core library (libuv) of older Node.js versions. This is fixed as of Node.js v7.1.0. Reference:

- https://github.com/paulmillr/chokidar/issues/499#issuecomment-227329780
- https://github.com/paulmillr/chokidar/issues/420#issuecomment-261848163
