### ISSUE TITLE
 When watch large files will trigger multiple change events

### ISSUE THREAD

**Issue by thankjava** [floatdrop/gulp-watch#278]
When I use it to monitor a directory, and then through the sftp or similar tools to remotely upload a larger file to this directory, you will find a trigger event multiple times, there is no way in this case only let it trigger An event reminder, because in fact, there should only be an add or change (overwrite upload) event.

**Comment by UltCombo** [comment]
I believe you should be able to configure the [`awaitWriteFinish`](https://github.com/paulmillr/chokidar#performance) option to fix that problem. E.g.:

```js
{
  awaitWriteFinish: {
    stabilityThreshold: 2000,
    pollInterval: 100
  }
}
```
