### ISSUE TITLE
Watched unexpected filepath

### ISSUE THREAD

**Issue by augustomurri** [floatdrop/gulp-watch#294]
Node.js version: `v8.9.1 linux x64`
gulp-watch version: `4.3.11`
Globs: `["/var/www/nutritioncenter.it/var/cache/misc/assets/js/tygh/*.js","/var/www/nutritioncenter.it/var/cache/misc/assets/design/themes/responsive/css/*.css","/var/www/pwa.nutritioncenter.it/css/"]`
Filepath: `/var/www/pwa.nutritioncenter.it/css/rtfheswrt.css`
Event: `unlink`
Process CWD: `/var/www/pwa.nutritioncenter.it`
Options:
```js
{
  "0": "generate-service-worker",
  "events": [
    "add",
    "change",
    "unlink"
  ],
  "ignoreInitial": true,
  "readDelay": 10
}
```

**Comment by floatdrop** [comment]
Dup https://github.com/floatdrop/gulp-watch/issues/251
