### ISSUE TITLE
No longer on NPM

### ISSUE THREAD

**Issue by magicspon** [floatdrop/gulp-watch#297]
https://www.npmjs.com/package/gulp-watch

any ideas? kinda dependant on it! 
cheers

**Comment by afortaleza** [comment]
Yeah, same here.

**Comment by kjschulz** [comment]
I get the following when trying install into a new project `No valid versions available for gulp-watch`.  Please advise.

**Comment by kjschulz** [comment]
FWIW, It's not 100% necessary obviously if you have a simplistic setup.  For instance, I'm able to use the following as a temporary workaround instead of `gulp-watch` in case that helps anybody:

```
var gulp = require('gulp');
var less = require('gulp-less');

gulp.task('less', function() {
  return gulp
    .src('./css/less/style.less')
    .pipe(less())
    .pipe(gulp.dest('./css'));
});
gulp.task('watch', function() {
  gulp.watch('./css/less/*.less', ['less']); 
});

gulp.task('default', ['watch']);
```

**Comment by magicspon** [comment]
https://status.npmjs.org/

**Comment by magicspon** [comment]
it's back:
https://www.npmjs.com/package/gulp-watch
