### ISSUE TITLE
gulp-watch: after installation and post the command: (npm: ls --depth = 0)

### ISSUE THREAD

**Issue by vicentetfreitas** [floatdrop/gulp-watch#300]
gulp-watch: after installation and post the command: (npm: ls --depth = 0) the following error below.
![erro gulp watch](https://user-images.githubusercontent.com/30361058/35236981-5a0514ea-ff90-11e7-90b2-2dacd3652f28.PNG)

**Comment by vicentetfreitas** [comment]
How to fix the fault after the command?

**Comment by floatdrop** [comment]
This is not issue with `gulp-watch`.
