### ISSUE TITLE
Support deleting removed or renamed files

### ISSUE THREAD

**Issue by xixixao** [floatdrop/gulp-watch#4]
``` javascript
var gulp = require('gulp');
var sass = require('gulp-sass');
var watch = require('gulp-watch');

gulp.task('default', function() {
    return gulp.src('./sass/*.scss')
        .pipe(watch())
        .pipe(sass())
        .pipe(gulp.dest('./dist/'));
});
```

It would be cool if output files of renamed or removed files got deleted (maybe automatically?). Would this be possible to implement with current gulp?

Edit: This of course is not simple, as the output name must be known, possibly requiring something from every gulp-plugin (I haven't gone through the API). If this requires changes in gulp I'll elevate the issue.

Edit2: For example, https://github.com/wearefractal/gulp-coffee/blob/master/index.js#L9 is just passing the file on, if it is null, without changing the extension.

**Comment by chester1000** [comment]
That worked for me too. Since `gulp-clean` is deprecated and solution here is spread across several posts, here's a **tl;dr**:

```bash
npm i gulp-filter del vinyl-paths --save-dev 
```
```coffeescript
del = require 'del'
vinylPaths = require 'vinyl-paths'
filter = require 'gulp-filter' # skip that if you're using `gulp-load-plugins`

deletedFilter = filter (file) -> file.event isnt 'deleted'

watch 'app/**/*.coffee'
  .pipe deletedFilter
  # some other pipes
  .pipe gulp.dest 'dist'

deletedFilter.restore end: true
  .pipe gulp.dest 'dist'
  .pipe vinylPaths del
```

**Comment by natew** [comment]
File.event seems to be undefined to me in the latest versions, what do you check to get the event type?

**Comment by ondaplana** [comment]
That worked for me:

```javascript
var watch = require('gulp-watch');
var filter = require('gulp-filter');
var vinylPaths = require('vinyl-paths');
var del = require('del');

gulp.task('watch-src', function() {
    var notDeletedFilter = filter(
      function(file) {
          return file.event !== 'unlink';
      },
      {restore: true}
    );

    notDeletedFilter.restore
        .pipe(gulp.dest('www'))
        .pipe(vinylPaths(function(file, cb) {
            del(file, cb);
        }));

    watch('src/client/**/*')
      .pipe(notDeletedFilter)
      .pipe(gulp.dest('www'));
});
```

**Comment by eksperimental** [comment]
Hi @ondaplana,
this doesn't seem to work for unliked directories
and renamed directories leave the old copy intact and create a copy of the new renamed folder.
any ideas how to solve this?

**Comment by UltCombo** [comment]
@eksperimental You will have to handle the `file.event === 'unlink'` case in your own code. This is how I've been doing it in my workflow: https://github.com/JSRocksHQ/slush-es20xx/blob/2de00c70dc52f990e7256f6cfb8019fc6665b6ac/tpl/env/node/gulpfile.js#L126-L130

**Comment by eksperimental** [comment]
@UltCombo well, after testing it for a while, renaming a dir never creates the "unlink" event. it behaves differently that when a file is renamed. which creates "add"  and "unlink". any way to solve this?

**Comment by UltCombo** [comment]
@eksperimental That's possibly an inconsistency in Chokidar or in a lower level (Node.js core/libuv/drivers/OS). The folks over at [Chokidar](https://github.com/paulmillr/chokidar) may be able to provide more help. 🙂
