### ISSUE TITLE
Update gaze  to support polling to allow watching for new and deleted files on network shares

### ISSUE THREAD

**Issue by F21** [floatdrop/gulp-watch#41]
I am using Ubuntu 14.04 and have a Windows 8.1 share mounted in my `fstab` using `cifs`.

I am using `gulp 3.6.2` and `gulp-watch 0.6.5`.

I noticed that changes to watched files are detected properly. However, new files and deletions are not detected.

Gaze has an option to force polling so that we can have changed and deleted evens when using networked file systems.

This change was introduce in `gaze 0.6.0`. Would you be able to update the dependency so we can force polling using `mode: 'polling'`?

**Comment by foxx** [comment]
Has this been resolved yet? I can't seem to enable polling

**Comment by floatdrop** [comment]
@foxx it should be #163
