### ISSUE TITLE
New files in empty or new directory are not watched

### ISSUE THREAD

**Issue by thebuilder** [floatdrop/gulp-watch#56]
I've noticed an issue when creating new files. 

I'm using the following watch, to look for all *.less* files in my *src* directory.
```
watch({glob: config.src + '**/*.less', name: 'LESS', emitOnGlob: false}, ['less'])
```
This works as expected, and new .less files gets detected.
Unless i create a *.less* file in an existing subdirectory that did not contain any *.less* files at the watch start. The files will not be detected before i restart the watch.

Is this an issue with globbing in general? If so, any idea of how to work around it?

**Comment by floatdrop** [comment]
@thebuilder gulp-watch@4.0.1 now uses chokidar, that fixes this issue.

**Comment by thebuilder** [comment]
Awesome!
________________________________
Fra: Vsevolod Strukchinsky<mailto:notifications@github.com>
Sendt: ý21-ý01-ý2015 19:23
Til: floatdrop/gulp-watch<mailto:gulp-watch@noreply.github.com>
Cc: Daniel Schmidt<mailto:dsc@insilico.dk>
Emne: Re: [gulp-watch] New files in empty or new directory are not watched (#56)


@thebuilder<https://github.com/thebuilder> gulp-watch@4.0.1 now uses chokidar, that fixes this issue.

**Comment by OlivierCuyp** [comment]
Still have the issue with empty folder.
Here is my code :

```js
gulp.task('clean:images', function () {
  return del.sync([
    config.img.out + '/**'
  ]);
});

gulp.task('bundle:images', ['clean:images'], function () {
  return gulp.src('assets/img/**/*.*')
    .pipe(gulp.dest('dist/img'));
});

gulp.task('watch:images', ['bundle:images'], function () {
  return gulp.watch('assets/img/**/*.*', ['bundle:images']);
});
```

**Comment by UltCombo** [comment]
@OlivierCuyp Are you actually using the [`gulp-watch` package](https://www.npmjs.com/package/gulp-watch)? Looks like you are using gulp's built-in `gulp.watch` method.
