### ISSUE TITLE
Issues with Windows path limit since 0.6.9

### ISSUE THREAD

**Issue by mekwall** [floatdrop/gulp-watch#57]
This is most likely happening due to lodash. I suggest you downgrade to continue support Windows users.

These issues are being discussed here:
https://github.com/lodash/lodash/issues/501
https://github.com/joyent/node/issues/6960

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages.
