### ISSUE TITLE
Emit on directory deletion?

### ISSUE THREAD

**Issue by demisx** [floatdrop/gulp-watch#70]
Is there a way to have `gulp-watch` react to a directory being deleted? Currently, I get an event when a new directory is added, but nothing, when a directory is being deleted, even if it had watched files in it.

Here is an test gulp task I am using:

``` js
gulp.task('watch-all', function () {
  watch({ glob: 'app/**/*'})
    .pipe(using())
});
```

Thank you.

**Comment by kuus** [comment]
@floatdrop is this working in the current version? Maybe I'm doing something wrong but it doesn't seem to react on directory deletion

**Comment by floatdrop** [comment]
@kuus `vinyl-file is not about directories (as gulp itself), so events for `create` and `delete` on directories are not emitted. If there is any files in this directory - then you will get `unlink ` event for these files.

**Comment by kuus** [comment]
@floatdrop I see, thanks for the explanation! I posted a (question on SO)[http://stackoverflow.com/questions/28474581/how-to-watch-a-src-folder-and-on-any-change-exactly-sync-onto-a-destination-fold]
