### ISSUE TITLE
Stops piping after error when gulp-watch is used

### ISSUE THREAD

**Issue by demisx** [floatdrop/gulp-watch#86]
I have a strange issue, that `gulp-sass()`stops piping files after a SASS error when used with `gulp-watch` (v0.7.1). 

1. When SASS files are error free, I see 'Writing sass' message each time I update a `*.scss` file. 
1. Then I deliberately introduce an error into one of the SASS files. I see an error message from `gulp-plumber` as I should. 
1. However, when I undo this error, I no longer see "Writing sass" message and no CSS files are being written to the `.build/` directory. I need to restart `gulp watch-sass` to make things go back to normal. 

Please note, that this doesn't happen if I use the `gulp.watch` method instead (see code snippets below).

**This is where the problem described above takes place:**
```coffeescript
# In gulpfile.coffee
sass = require("gulp-sass")
... ... ...
gulp.task "watch-sass", ->
  watch
    glob: filePath.appDir + "/**/*.scss"
  .pipe plumber()
  .pipe sass()
  .pipe using prefix: "Writing sass" 
  .pipe gulp.dest('.build/')
  return  
```

**However, no such problem using `gulp.watch`:**
```coffeescript
# In gulpfile.coffee
sass = require("gulp-sass")
... ... ...
gulp.task "watch-sass", -> 
  gulp.watch filePath.appDir + "/**/*.scss", (file) ->
    gulp.src file.path
    .pipe plumber()
    .pipe sass()
    .pipe using prefix: "Writing sass" 
    .pipe gulp.dest('.build/')
    return
```

**Comment by floatdrop** [comment]
I guess this is not problem with gulp-watch (from @demisx comment). Feel free to reopen if it is not.

@sheo13666 try to update on `4.0.0` - if this still a problem, file new issue.
