### ISSUE TITLE
"glob should be String or Array, not object" error - but String is given

### ISSUE THREAD

**Issue by lumio** [floatdrop/gulp-watch#90]
Hello,

I'm using gulp-watch 1.0.7 and I'm trying to watch even new files with it.
Therefore I have a watch task like this:

```
gulp.task('watch', ['wiredep', 'styles'] ,function () {
  watch({ glob: ['app/components/**/*.sass'] }, function() {
    gulp.start('build');
  });
  watch({ glob: ['app/components/**/*.js'] }, function() {
    gulp.start('scripts');
  });
  watch({ glob: ['app/images/**/*'] }, function() {
    gulp.start('images');
  });
  watch('bower.json', function() {
    gulp.start('wiredep');
  });
});
```

I tried it with an Array (as you can see here) and a String, but both led to the error `glob should be String or Array, not object`

After a brief debugging session I added the following line to the modules index.js after line 18:

```
if (globs.glob) globs = globs.glob;
```

I'm not sure if that is a clean solution, but it would work.

**Comment by andela-gjames** [comment]
Awesome, spent the last hour trying to make gulp listen to new files changes, but it does not work for deleted files, even though the function is called, the file is not removed from the build DIR
